const Routes = [
  { method: 'get', path: '/Users/Counts', controller: 'User', action: 'GetUsersCounts' },
  { method: 'get', path: '/Users/List', controller: 'User', action: 'GetUsersList' },
  { method: 'get', path: '/Users', controller: 'User', action: 'GetUsers' },
  { method: 'get', path: '/Users/:userId', controller: 'User', action: 'GetUser' },
  { method: 'post', path: '/Users/Register', controller: 'User', action: 'Register' },
  { method: 'post', path: '/Users', controller: 'User', action: 'AddUser' },
  { method: 'put', path: '/Users/RemoveUsers', controller: 'User', action: 'RemoveUsers' },
  { method: 'put', path: '/Users', controller: 'User', action: 'UpdateUser' },
  { method: 'delete', path: '/Users/:userId', controller: 'User', action: 'DeleteUser' },

  { method: 'get', path: '/Profile/Getusersalt/:userId', controller: 'Profile', action: 'Getusersalt' },
  { method: 'get', path: '/Profile/Getuserbyemail/:email', controller: 'Profile', action: 'Getuserbyemail' },
  { method: 'get', path: '/Profile/Getuserbyusername/:username', controller: 'Profile', action: 'Getuserbyusername' },
  { method: 'get', path: '/Profile/Gettablemeta', controller: 'Profile', action: 'Gettablemeta' },
  { method: 'get', path: '/Profile/Getusername', controller: 'Profile', action: 'Getusername' },
  { method: 'get', path: '/Profile/Getmeta', controller: 'Profile', action: 'Getmeta' },
  { method: 'post', path: '/Profile/Changepassword', controller: 'Profile', action: 'Changepassword' },
  { method: 'post', path: '/Profile/Savetablemeta', controller: 'Profile', action: 'Savetablemeta' },
  { method: 'put', path: '/Profile/Changepasswordbyrequest', controller: 'Profile', action: 'Changepasswordbyrequest' },
  { method: 'delete', path: '/Profile/Resettablemeta/:metaKey', controller: 'Profile', action: 'Resettablemeta' },

  { method: 'get', path: '/Profile/GetTableConfig', controller: 'Profile', action: 'GetTableConfig' },
  { method: 'post', path: '/Profile/SaveTableConfig', controller: 'Profile', action: 'SaveTableConfig' },
  { method: 'delete', path: '/Profile/ResetTableConfig', controller: 'Profile', action: 'ResetTableConfig' },

  { method: 'get', path: '/Roles/GetCount', controller: 'Role', action: 'GetRolescount' },
  { method: 'get', path: '/Roles', controller: 'Role', action: 'GetRoles' },
  { method: 'get', path: '/Roles/GetActiveuserprivileges', controller: 'Role', action: 'GetActiveuserprivileges' },
  { method: 'get', path: '/Roles/Getprivileges', controller: 'Role', action: 'Getprivileges' },
  { method: 'get', path: '/Roles/Getprivilegegroups', controller: 'Role', action: 'Getprivilegegroups' },
  { method: 'get', path: '/Roles/:roleId', controller: 'Role', action: 'GetRole' },
  { method: 'get', path: '/Roles/Getprivilegesbyuserid/:userId', controller: 'Role', action: 'Getprivilegesbyuserid' },
  { method: 'post', path: '/Roles', controller: 'Role', action: 'AddRole' },
  { method: 'put', path: '/Roles', controller: 'Role', action: 'UpdateRole' },
  { method: 'delete', path: '/Roles/:roleId', controller: 'Role', action: 'DeleteRole' },

  { method: 'get', path: '/Usernotifications/GetLastUsernotificationsbyUserid/:userId', controller: 'Usernotification', action: 'GetLastUsernotificationsbyUserid' },
  { method: 'get', path: '/Usernotifications/ReadAllNotificationByUser/:userId', controller: 'Usernotification', action: 'ReadAllNotificationByUser' },
  { method: 'get', path: '/Usernotifications/ShowAllNotificationByUser/:userId', controller: 'Usernotification', action: 'ShowAllNotificationByUser' },
  { method: 'get', path: '/Usernotifications/GetUnreadNotificationCountByUser/:userId', controller: 'Usernotification', action: 'GetUnreadNotificationCountByUser' },
  { method: 'get', path: '/Usernotifications/GetUnshowedNotificationCountByUser/:userId', controller: 'Usernotification', action: 'GetUnshowedNotificationCountByUser' },
  { method: 'get', path: '/Usernotifications/GetUsernotificationsbyUserid/:userId', controller: 'Usernotification', action: 'GetUsernotificationsbyUserid' },
  { method: 'get', path: '/Usernotifications', controller: 'Usernotification', action: 'GetUsernotifications' },
  { method: 'post', path: '/Usernotifications/AddUsernotificationbyrole', controller: 'Usernotification', action: 'AddUsernotificationbyrole' },
  { method: 'put', path: '/Usernotifications/Editrecord', controller: 'Usernotification', action: 'UpdateUsernotifications' },
  { method: 'delete', path: '/Usernotifications/DeleteUsernotificationbyidreaded/:userId', controller: 'Usernotification', action: 'DeleteUsernotificationbyidreaded' },
  { method: 'delete', path: '/Usernotifications/DeleteUsernotificationbyid/:userId', controller: 'Usernotification', action: 'DeleteUsernotificationbyid' },
  { method: 'delete', path: '/Usernotifications/:notificationId', controller: 'Usernotification', action: 'DeleteUsernotification' },
]

module.exports = Routes