const Priveleges = [
    { code: 'admin', text: { en: 'Admin', tr: 'Admin' },  group: { en: 'Base', tr: 'Temel' } },
    { code: 'basic', text: { en: 'Basic', tr: 'Basit Ayarlar' },  group: { en: 'Base', tr: 'Temel' } },
    { code: 'rolescreen',       text: { en: 'Roles Screen',      tr: 'Roller Veri' },             group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleview',         text: { en: 'Roles View',        tr: 'Roller Görüntüleme' },      group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleadd',          text: { en: 'Roles Add',         tr: 'Roller Oluşturma' },        group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleupdate',       text: { en: 'Roles Update',      tr: 'Roller Güncelleme' },       group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roledelete',       text: { en: 'Roles Delete',      tr: 'Roller Silme' },            group: { en: 'Roles', tr: 'Roller' } },
    { code: 'rolemanageview',   text: { en: 'Roles Manage View', tr: 'Roller Görünüm Ayarlama' }, group: { en: 'Roles', tr: 'Roller' } },
    { code: 'rolegetreport',    text: { en: 'Roles Get Report',  tr: 'Roller Rapor Alma' },       group: { en: 'Roles', tr: 'Roller' } },
    { code: 'rolenotification', text: { en: 'Roles Notification',tr: 'Roller Bildirim Alma' },    group: { en: 'Roles', tr: 'Roller' } },
    { code: 'mailsettingscreen',       text: { en: 'Mailsettings Screen',      tr: 'Mail Ayarları Veri' },             group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingview',         text: { en: 'Mailsettings View',        tr: 'Mail Ayarları Görüntüleme' },      group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingadd',          text: { en: 'Mailsettings Add',         tr: 'Mail Ayarları Oluşturma' },        group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingupdate',       text: { en: 'Mailsettings Update',      tr: 'Mail Ayarları Güncelleme' },       group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingdelete',       text: { en: 'Mailsettings Delete',      tr: 'Mail Ayarları Silme' },            group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingmanageview',   text: { en: 'Mailsettings Manage View', tr: 'Mail Ayarları Görünüm Ayarlama' }, group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettinggetreport',    text: { en: 'Mailsettings Get Report',  tr: 'Mail Ayarları Rapor Alma' },       group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingnotification', text: { en: 'Mailsettings Notification',tr: 'Mail Ayarları Bildirim Alma' },    group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'rulescreen',       text: { en: 'Rules Screen',      tr: 'Kurallar Veri' },             group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleview',         text: { en: 'Rules View',        tr: 'Kurallar Görüntüleme' },      group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleadd',          text: { en: 'Rules Add',         tr: 'Kurallar Oluşturma' },        group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleupdate',       text: { en: 'Rules Update',      tr: 'Kurallar Güncelleme' },       group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruledelete',       text: { en: 'Rules Delete',      tr: 'Kurallar Silme' },            group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'rulemanageview',   text: { en: 'Rules Manage View', tr: 'Kurallar Görünüm Ayarlama' }, group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'rulegetreport',    text: { en: 'Rules Get Report',  tr: 'Kurallar Rapor Alma' },       group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'rulenotification', text: { en: 'Rules Notification',tr: 'Kurallar Bildirim Alma' },    group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'userscreen',         text: { en: 'Users Screen',           tr: 'Kullanıcılar Veri' },               group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userview',           text: { en: 'Users View',             tr: 'Kullanıcılar Görüntüleme' },        group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'useradd',            text: { en: 'Users Add',              tr: 'Kullanıcılar Oluşturma' },          group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdate',         text: { en: 'Users Update',           tr: 'Kullanıcılar Güncelleme' },         group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userremove',         text: { en: 'Users Remove',           tr: 'Kullanıcılar Kurumdan Çıkartma' },  group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdatecase',     text: { en: 'Users Update Case',      tr: 'Kullanıcılar Durum Güncelleme' },   group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdatemovement', text: { en: 'Users Update Movement',  tr: 'Kullanıcılar Hareket Güncelleme' }, group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userdeletemovement', text: { en: 'Users Delete Movement',  tr: 'Kullanıcılar Hareket Silme' },      group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userdelete',         text: { en: 'Users Delete',           tr: 'Kullanıcılar Silme' },              group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'usermanageview',     text: { en: 'Users Manage View',      tr: 'Kullanıcılar Görünüm Ayarlama' },   group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'usergetreport',      text: { en: 'Users Get Report',       tr: 'Kullanıcılar Rapor Alma' },         group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'usernotification',   text: { en: 'Users Notification',     tr: 'Kullanıcılar Bildirim Alma' },      group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'approveview',                text: { en: 'Approve Page View',              tr: 'Onay Bekleyen İşlemler Görüntüleme' },    group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'approvalrequestcreen',       text: { en: 'Approval Requests Screen',       tr: 'Onay Talepleri Veri' },              group: { en: 'Approval Requests', tr: 'Onay Talepleri' } },
    { code: 'approvalrequestview',        text: { en: 'Approval Requests View',         tr: 'Onay Talepleri Görüntüleme' },       group: { en: 'Approval Requests', tr: 'Onay Talepleri' } },
    { code: 'approvalrequestupdate',      text: { en: 'Approval Requests Update',          tr: 'Onay Talepleri Güncelleme' },     group: { en: 'Approval Requests', tr: 'Onay Talepleri' } },
    { code: 'casescreen',       text: { en: 'Cases Screen',      tr: 'Durumlar Veri' },             group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'caseview',         text: { en: 'Cases View',        tr: 'Durumlar Görüntüleme' },      group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'caseadd',          text: { en: 'Cases Add',         tr: 'Durumlar Oluşturma' },        group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'caseupdate',       text: { en: 'Cases Update',      tr: 'Durumlar Güncelleme' },       group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casedelete',       text: { en: 'Cases Delete',      tr: 'Durumlar Silme' },            group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casemanageview',   text: { en: 'Cases Manage View', tr: 'Durumlar Görünüm Ayarlama' }, group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casegetreport',    text: { en: 'Cases Get Report',  tr: 'Durumlar Rapor Alma' },       group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casenotification', text: { en: 'Cases Notification',tr: 'Durumlar Bildirim Alma' },    group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'doctordefinescreen',       text: { en: 'Doctor Defines Screen',      tr: 'Doktor Tanımları Veri' },             group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefineview',         text: { en: 'Doctor Defines View',        tr: 'Doktor Tanımları Görüntüleme' },      group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefineadd',          text: { en: 'Doctor Defines Add',         tr: 'Doktor Tanımları Oluşturma' },        group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefineupdate',       text: { en: 'Doctor Defines Update',      tr: 'Doktor Tanımları Güncelleme' },       group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefinedelete',       text: { en: 'Doctor Defines Delete',      tr: 'Doktor Tanımları Silme' },            group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefinemanageview',   text: { en: 'Doctor Defines Manage View', tr: 'Doktor Tanımları Görünüm Ayarlama' }, group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefinegetreport',    text: { en: 'Doctor Defines Get Report',  tr: 'Doktor Tanımları Rapor Alma' },       group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefinenotification', text: { en: 'Doctor Defines Notification',tr: 'Doktor Tanımları Bildirim Alma' },    group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'paymenttypescreen',       text: { en: 'Payment Type Screen',      tr: 'Ödeme Türleri Veri' },             group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypeview',         text: { en: 'Payment Type View',        tr: 'Ödeme Türleri Görüntüleme' },      group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypeadd',          text: { en: 'Payment Type Add',         tr: 'Ödeme Türleri Oluşturma' },        group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypeupdate',       text: { en: 'Payment Type Update',      tr: 'Ödeme Türleri Güncelleme' },       group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypedelete',       text: { en: 'Payment Type Delete',      tr: 'Ödeme Türleri Silme' },            group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypemanageview',   text: { en: 'Payment Type Manage View', tr: 'Ödeme Türleri Görünüm Ayarlama' }, group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypegetreport',    text: { en: 'Payment Type Get Report',  tr: 'Ödeme Türleri Rapor Alma' },       group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypenotification', text: { en: 'Payment Type Notification',tr: 'Ödeme Türleri Bildirim Alma' },    group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'locationscreen',       text: { en: 'Locations Screen',      tr: 'Bölgeler Veri' },             group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationview',         text: { en: 'Locations View',        tr: 'Bölgeler Görüntüleme' },      group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationadd',          text: { en: 'Locations Add',         tr: 'Bölgeler Oluşturma' },        group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationupdate',       text: { en: 'Locations Update',      tr: 'Bölgeler Güncelleme' },       group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationdelete',       text: { en: 'Locations Delete',      tr: 'Bölgeler Silme' },            group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationmanageview',   text: { en: 'Locations Manage View', tr: 'Bölgeler Görünüm Ayarlama' }, group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationgetreport',    text: { en: 'Locations Get Report',  tr: 'Bölgeler Rapor Alma' },       group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationnotification', text: { en: 'Locations Notification',tr: 'Bölgeler Bildirim Alma' },    group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'stockdefinescreen',       text: { en: 'Stock Defines Screen',      tr: 'Ürün Tanımları Veri' },             group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefineview',         text: { en: 'Stock Defines View',        tr: 'Ürün Tanımları Görüntüleme' },      group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefineadd',          text: { en: 'Stock Defines Add',         tr: 'Ürün Tanımları Oluşturma' },        group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefineupdate',       text: { en: 'Stock Defines Update',      tr: 'Ürün Tanımları Güncelleme' },       group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefinedelete',       text: { en: 'Stock Defines Delete',      tr: 'Ürün Tanımları Silme' },            group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefinemanageview',   text: { en: 'Stock Defines Manage View', tr: 'Ürün Tanımları Görünüm Ayarlama' }, group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefinegetreport',    text: { en: 'Stock Defines Get Report',  tr: 'Ürün Tanımları Rapor Alma' },       group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefinenotification', text: { en: 'Stock Defines Notification',tr: 'Ürün Tanımları Bildirim Alma' },    group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'warehousescreen',       text: { en: 'Warehouses Screen',      tr: 'Depolar Veri' },             group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehouseview',         text: { en: 'Warehouses View',        tr: 'Depolar Görüntüleme' },      group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehouseadd',          text: { en: 'Warehouses Add',         tr: 'Depolar Oluşturma' },        group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehouseupdate',       text: { en: 'Warehouses Update',      tr: 'Depolar Güncelleme' },       group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehousedelete',       text: { en: 'Warehouses Delete',      tr: 'Depolar Silme' },            group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehousemanageview',   text: { en: 'Warehouses Manage View', tr: 'Depolar Görünüm Ayarlama' }, group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehousegetreport',    text: { en: 'Warehouses Get Report',  tr: 'Depolar Rapor Alma' },       group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehousenotification', text: { en: 'Warehouses Notification',tr: 'Depolar Bildirim Alma' },    group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'stockscreen',       text: { en: 'Stocks Screen',      tr: 'Ürünler Veri' },             group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockview',         text: { en: 'Stocks View',        tr: 'Ürünler Görüntüleme' },      group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockadd',          text: { en: 'Stocks Add',         tr: 'Ürünler Oluşturma' },        group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockupdate',       text: { en: 'Stocks Update',      tr: 'Ürünler Güncelleme' },       group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockdelete',       text: { en: 'Stocks Delete',      tr: 'Ürünler Silme' },            group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockmanageview',   text: { en: 'Stocks Manage View', tr: 'Ürünler Görünüm Ayarlama' }, group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockgetreport',    text: { en: 'Stocks Get Report',  tr: 'Ürünler Rapor Alma' },       group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stocknotification', text: { en: 'Stocks Notification',tr: 'Ürünler Bildirim Alma' },    group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'visitscreen',       text: { en: 'Visits Screen',      tr: 'Ziyaretler Veri' },             group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitview',         text: { en: 'Visits View',        tr: 'Ziyaretler Görüntüleme' },      group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitadd',          text: { en: 'Visits Add',         tr: 'Ziyaretler Oluşturma' },        group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitupdate',       text: { en: 'Visits Update',      tr: 'Ziyaretler Güncelleme' },       group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitdelete',       text: { en: 'Visits Delete',      tr: 'Ziyaretler Silme' },            group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitmanageview',   text: { en: 'Visits Manage View', tr: 'Ziyaretler Görünüm Ayarlama' }, group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitgetreport',    text: { en: 'Visits Get Report',  tr: 'Ziyaretler Rapor Alma' },       group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitapprove',      text: { en: 'Visits Approve',     tr: 'Ziyaretler Onaylama' },         group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitnotification', text: { en: 'Visits Notification',tr: 'Ziyaretler Bildirim Alma' },    group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'paymentplanscreen',       text: { en: 'Payment Plans Screen',      tr: 'Ödeme Planları Veri' },             group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplanview',         text: { en: 'Payment Plans View',        tr: 'Ödeme Planları Görüntüleme' },      group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplanadd',          text: { en: 'Payment Plans Add',         tr: 'Ödeme Planları Oluşturma' },        group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplanupdate',       text: { en: 'Payment Plans Update',      tr: 'Ödeme Planları Güncelleme' },       group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplandelete',       text: { en: 'Payment Plans Delete',      tr: 'Ödeme Planları Silme' },            group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplanmanageview',   text: { en: 'Payment Plans Manage View', tr: 'Ödeme Planları Görünüm Ayarlama' }, group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplangetreport',    text: { en: 'Payment Plans Get Report',  tr: 'Ödeme Planları Rapor Alma' },       group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplannotification', text: { en: 'Payment Plans Notification',tr: 'Ödeme Planları Bildirim Alma' },    group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    ]
    
    module.exports = Priveleges