const Priveleges = [
    { code: 'admin', text: { en: 'Admin', tr: 'Admin' },  group: { en: 'Base', tr: 'Temel' } },
    { code: 'basic', text: { en: 'Basic', tr: 'Basit Ayarlar' },  group: { en: 'Base', tr: 'Temel' } },
    { code: 'rolescreen',       text: { en: 'Roles Screen',      tr: 'Roller Veri' },             group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleview',         text: { en: 'Roles View',        tr: 'Roller Görüntüleme' },      group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleadd',          text: { en: 'Roles Add',         tr: 'Roller Oluşturma' },        group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleupdate',       text: { en: 'Roles Update',      tr: 'Roller Güncelleme' },       group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roledelete',       text: { en: 'Roles Delete',      tr: 'Roller Silme' },            group: { en: 'Roles', tr: 'Roller' } },
    { code: 'rolenotification', text: { en: 'Roles Notification',tr: 'Roller Bildirim Alma' },    group: { en: 'Roles', tr: 'Roller' } },
    { code: 'mailsettingscreen',       text: { en: 'Mailsettings Screen',      tr: 'Mail Ayarları Veri' },             group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingview',         text: { en: 'Mailsettings View',        tr: 'Mail Ayarları Görüntüleme' },      group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingadd',          text: { en: 'Mailsettings Add',         tr: 'Mail Ayarları Oluşturma' },        group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingupdate',       text: { en: 'Mailsettings Update',      tr: 'Mail Ayarları Güncelleme' },       group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingdelete',       text: { en: 'Mailsettings Delete',      tr: 'Mail Ayarları Silme' },            group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingnotification', text: { en: 'Mailsettings Notification',tr: 'Mail Ayarları Bildirim Alma' },    group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'rulescreen',       text: { en: 'Rules Screen',      tr: 'Kurallar Veri' },             group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleview',         text: { en: 'Rules View',        tr: 'Kurallar Görüntüleme' },      group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleadd',          text: { en: 'Rules Add',         tr: 'Kurallar Oluşturma' },        group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleupdate',       text: { en: 'Rules Update',      tr: 'Kurallar Güncelleme' },       group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruledelete',       text: { en: 'Rules Delete',      tr: 'Kurallar Silme' },            group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'rulenotification', text: { en: 'Rules Notification',tr: 'Kurallar Bildirim Alma' },    group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'userscreen',         text: { en: 'Users Screen',           tr: 'Kullanıcılar Veri' },               group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userview',           text: { en: 'Users View',             tr: 'Kullanıcılar Görüntüleme' },        group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'useradd',            text: { en: 'Users Add',              tr: 'Kullanıcılar Oluşturma' },          group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdate',         text: { en: 'Users Update',           tr: 'Kullanıcılar Güncelleme' },         group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userremove',         text: { en: 'Users Remove',           tr: 'Kullanıcılar Kurumdan Çıkartma' },  group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdatecase',     text: { en: 'Users Update Case',      tr: 'Kullanıcılar Durum Güncelleme' },   group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdatemovement', text: { en: 'Users Update Movement',  tr: 'Kullanıcılar Hareket Güncelleme' }, group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userdeletemovement', text: { en: 'Users Delete Movement',  tr: 'Kullanıcılar Hareket Silme' },      group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userdelete',         text: { en: 'Users Delete',           tr: 'Kullanıcılar Silme' },              group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'usernotification',   text: { en: 'Users Notification',     tr: 'Kullanıcılar Bildirim Alma' },      group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'approvalrequestcreen',       text: { en: 'Approval Requests Screen',       tr: 'Onay Talepleri Veri' },              group: { en: 'Approval Requests', tr: 'Onay Talepleri' } },
    { code: 'approvalrequestview',        text: { en: 'Approval Requests View',         tr: 'Onay Talepleri Görüntüleme' },       group: { en: 'Approval Requests', tr: 'Onay Talepleri' } },
    { code: 'approvalrequestupdate',      text: { en: 'Approval Requests Update',       tr: 'Onay Talepleri Güncelleme' },        group: { en: 'Approval Requests', tr: 'Onay Talepleri' } },
    { code: 'doctordefinescreen',       text: { en: 'Doctor Defines Screen',      tr: 'Doktor Tanımları Veri' },             group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefineview',         text: { en: 'Doctor Defines View',        tr: 'Doktor Tanımları Görüntüleme' },      group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefineadd',          text: { en: 'Doctor Defines Add',         tr: 'Doktor Tanımları Oluşturma' },        group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefineupdate',       text: { en: 'Doctor Defines Update',      tr: 'Doktor Tanımları Güncelleme' },       group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefinedelete',       text: { en: 'Doctor Defines Delete',      tr: 'Doktor Tanımları Silme' },            group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'doctordefinenotification', text: { en: 'Doctor Defines Notification',tr: 'Doktor Tanımları Bildirim Alma' },    group: { en: 'Doctor Defines', tr: 'Doktor Tanımları' } },
    { code: 'paymenttypescreen',       text: { en: 'Payment Type Screen',      tr: 'Ödeme Türleri Veri' },             group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypeview',         text: { en: 'Payment Type View',        tr: 'Ödeme Türleri Görüntüleme' },      group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypeadd',          text: { en: 'Payment Type Add',         tr: 'Ödeme Türleri Oluşturma' },        group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypeupdate',       text: { en: 'Payment Type Update',      tr: 'Ödeme Türleri Güncelleme' },       group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypedelete',       text: { en: 'Payment Type Delete',      tr: 'Ödeme Türleri Silme' },            group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'paymenttypenotification', text: { en: 'Payment Type Notification',tr: 'Ödeme Türleri Bildirim Alma' },    group: { en: 'Payment Types', tr: 'Ödeme Türleri' } },
    { code: 'locationscreen',       text: { en: 'Locations Screen',      tr: 'Bölgeler Veri' },             group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationview',         text: { en: 'Locations View',        tr: 'Bölgeler Görüntüleme' },      group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationadd',          text: { en: 'Locations Add',         tr: 'Bölgeler Oluşturma' },        group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationupdate',       text: { en: 'Locations Update',      tr: 'Bölgeler Güncelleme' },       group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationdelete',       text: { en: 'Locations Delete',      tr: 'Bölgeler Silme' },            group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'locationnotification', text: { en: 'Locations Notification',tr: 'Bölgeler Bildirim Alma' },    group: { en: 'Locations', tr: 'Bölgeler' } },
    { code: 'stockdefinescreen',       text: { en: 'Stock Defines Screen',      tr: 'Ürün Tanımları Veri' },             group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefineview',         text: { en: 'Stock Defines View',        tr: 'Ürün Tanımları Görüntüleme' },      group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefineadd',          text: { en: 'Stock Defines Add',         tr: 'Ürün Tanımları Oluşturma' },        group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefineupdate',       text: { en: 'Stock Defines Update',      tr: 'Ürün Tanımları Güncelleme' },       group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefinedelete',       text: { en: 'Stock Defines Delete',      tr: 'Ürün Tanımları Silme' },            group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'stockdefinenotification', text: { en: 'Stock Defines Notification',tr: 'Ürün Tanımları Bildirim Alma' },    group: { en: 'Stock Defines', tr: 'Ürün Tanımları' } },
    { code: 'warehousescreen',       text: { en: 'Warehouses Screen',      tr: 'Depolar Veri' },             group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehouseview',         text: { en: 'Warehouses View',        tr: 'Depolar Görüntüleme' },      group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehouseadd',          text: { en: 'Warehouses Add',         tr: 'Depolar Oluşturma' },        group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehouseupdate',       text: { en: 'Warehouses Update',      tr: 'Depolar Güncelleme' },       group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehousedelete',       text: { en: 'Warehouses Delete',      tr: 'Depolar Silme' },            group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'warehousenotification', text: { en: 'Warehouses Notification',tr: 'Depolar Bildirim Alma' },    group: { en: 'Warehouses', tr: 'Depolar' } },
    { code: 'stockscreen',       text: { en: 'Stocks Screen',      tr: 'Ürünler Veri' },             group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockview',         text: { en: 'Stocks View',        tr: 'Ürünler Görüntüleme' },      group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockadd',          text: { en: 'Stocks Add',         tr: 'Ürünler Oluşturma' },        group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockupdate',       text: { en: 'Stocks Update',      tr: 'Ürünler Güncelleme' },       group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stockdelete',       text: { en: 'Stocks Delete',      tr: 'Ürünler Silme' },            group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'stocknotification', text: { en: 'Stocks Notification',tr: 'Ürünler Bildirim Alma' },    group: { en: 'Stocks', tr: 'Ürünler' } },
    { code: 'visitscreen',       text: { en: 'Visits Screen',      tr: 'Ziyaretler Veri' },             group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitview',         text: { en: 'Visits View',        tr: 'Ziyaretler Görüntüleme' },      group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitmanageall',    text: { en: 'Visits Manage All',  tr: 'Ziyaretler Tüm Kontrol' },      group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitadd',          text: { en: 'Visits Add',         tr: 'Ziyaretler Oluşturma' },        group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitupdate',       text: { en: 'Visits Update',      tr: 'Ziyaretler Güncelleme' },       group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitdelete',       text: { en: 'Visits Delete',      tr: 'Ziyaretler Silme' },            group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitapprove',      text: { en: 'Visits Approve',     tr: 'Ziyaretler Onaylama' },         group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'visitnotification', text: { en: 'Visits Notification',tr: 'Ziyaretler Bildirim Alma' },    group: { en: 'Visits', tr: 'Ziyaretler' } },
    { code: 'paymentplanscreen',       text: { en: 'Payment Plans Screen',      tr: 'Ödeme Planları Veri' },             group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplanview',         text: { en: 'Payment Plans View',        tr: 'Ödeme Planları Görüntüleme' },      group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplanadd',          text: { en: 'Payment Plans Add',         tr: 'Ödeme Planları Oluşturma' },        group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplanupdate',       text: { en: 'Payment Plans Update',      tr: 'Ödeme Planları Güncelleme' },       group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplandelete',       text: { en: 'Payment Plans Delete',      tr: 'Ödeme Planları Silme' },            group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    { code: 'paymentplannotification', text: { en: 'Payment Plans Notification',tr: 'Ödeme Planları Bildirim Alma' },    group: { en: 'Payment Plans', tr: 'Ödeme Planaları' } },
    ]
    
    module.exports = Priveleges