const Priveleges = [
    { code: 'admin', text: { en: 'Admin', tr: 'Admin' },  group: { en: 'Base', tr: 'Temel' } },
    { code: 'basic', text: { en: 'Basic', tr: 'Basit Ayarlar' },  group: { en: 'Base', tr: 'Temel' } },
    
    { code: 'bedscreen',       text: { en: 'Beds Screen',      tr: 'Yataklar Veri' },             group: { en: 'Beds', tr: 'Yataklar' } },
    { code: 'bedview',         text: { en: 'Beds View',        tr: 'Yataklar Görüntüleme' },      group: { en: 'Beds', tr: 'Yataklar' } },
    { code: 'bedadd',          text: { en: 'Beds Add',         tr: 'Yataklar Oluşturma' },        group: { en: 'Beds', tr: 'Yataklar' } },
    { code: 'bedupdate',       text: { en: 'Beds Update',      tr: 'Yataklar Güncelleme' },       group: { en: 'Beds', tr: 'Yataklar' } },
    { code: 'beddelete',       text: { en: 'Beds Delete',      tr: 'Yataklar Silme' },            group: { en: 'Beds', tr: 'Yataklar' } },
    { code: 'bedgetreport',    text: { en: 'Beds Get Report',  tr: 'Yataklar Rapor Alma' },       group: { en: 'Beds', tr: 'Yataklar' } },
    { code: 'bedmanageview',   text: { en: 'Beds Manage View', tr: 'Yataklar Görünüm Ayarlama' }, group: { en: 'Beds', tr: 'Yataklar' } },
    { code: 'bednotification', text: { en: 'Beds Notification',tr: 'Yataklar Bildirim Alma' },    group: { en: 'Beds', tr: 'Yataklar' } },
    
    { code: 'rolescreen',       text: { en: 'Roles Screen',      tr: 'Roller Veri' },             group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleview',         text: { en: 'Roles View',        tr: 'Roller Görüntüleme' },      group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleadd',          text: { en: 'Roles Add',         tr: 'Roller Oluşturma' },        group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roleupdate',       text: { en: 'Roles Update',      tr: 'Roller Güncelleme' },       group: { en: 'Roles', tr: 'Roller' } },
    { code: 'roledelete',       text: { en: 'Roles Delete',      tr: 'Roller Silme' },            group: { en: 'Roles', tr: 'Roller' } },
    { code: 'rolemanageview',   text: { en: 'Roles Manage View', tr: 'Roller Görünüm Ayarlama' }, group: { en: 'Roles', tr: 'Roller' } },
    { code: 'rolegetreport',    text: { en: 'Roles Get Report',  tr: 'Roller Rapor Alma' },       group: { en: 'Roles', tr: 'Roller' } },
    { code: 'rolenotification', text: { en: 'Roles Notification',tr: 'Roller Bildirim Alma' },    group: { en: 'Roles', tr: 'Roller' } },

    { code: 'casescreen',       text: { en: 'Cases Screen',      tr: 'Durumlar Veri' },             group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'caseview',         text: { en: 'Cases View',        tr: 'Durumlar Görüntüleme' },      group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'caseadd',          text: { en: 'Cases Add',         tr: 'Durumlar Oluşturma' },        group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'caseupdate',       text: { en: 'Cases Update',      tr: 'Durumlar Güncelleme' },       group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casedelete',       text: { en: 'Cases Delete',      tr: 'Durumlar Silme' },            group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casemanageview',   text: { en: 'Cases Manage View', tr: 'Durumlar Görünüm Ayarlama' }, group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casegetreport',    text: { en: 'Cases Get Report',  tr: 'Durumlar Rapor Alma' },       group: { en: 'Cases', tr: 'Durumlar' } },
    { code: 'casenotification', text: { en: 'Cases Notification',tr: 'Durumlar Bildirim Alma' },    group: { en: 'Cases', tr: 'Durumlar' } },
    
    { code: 'costumertypescreen',       text: { en: 'Costumertypes Screen',      tr: 'Müşteri Türleri Veri' },             group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    { code: 'costumertypeview',         text: { en: 'Costumertypes View',        tr: 'Müşteri Türleri Görüntüleme' },      group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    { code: 'costumertypeadd',          text: { en: 'Costumertypes Add',         tr: 'Müşteri Türleri Oluşturma' },        group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    { code: 'costumertypeupdate',       text: { en: 'Costumertypes Update',      tr: 'Müşteri Türleri Güncelleme' },       group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    { code: 'costumertypedelete',       text: { en: 'Costumertypes Delete',      tr: 'Müşteri Türleri Silme' },            group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    { code: 'costumertypemanageview',   text: { en: 'Costumertypes Manage View', tr: 'Müşteri Türleri Görünüm Ayarlama' }, group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    { code: 'costumertypegetreport',    text: { en: 'Costumertypes Get Report',  tr: 'Müşteri Türleri Rapor Alma' },       group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    { code: 'costumertypenotification', text: { en: 'Costumertypes Notification',tr: 'Müşteri Türleri Bildirim Alma' },    group: { en: 'Costumertypes', tr: 'Müşteri Türleri' } },
    
    { code: 'departmentscreen',       text: { en: 'Departments Screen',      tr: 'Departmanlar Veri' },             group: { en: 'Departments', tr: 'Departmanlar' } },
    { code: 'departmentview',         text: { en: 'Departments View',        tr: 'Departmanlar Görüntüleme' },      group: { en: 'Departments', tr: 'Departmanlar' } },
    { code: 'departmentadd',          text: { en: 'Departments Add',         tr: 'Departmanlar Oluşturma' },        group: { en: 'Departments', tr: 'Departmanlar' } },
    { code: 'departmentupdate',       text: { en: 'Departments Update',      tr: 'Departmanlar Güncelleme' },       group: { en: 'Departments', tr: 'Departmanlar' } },
    { code: 'departmentdelete',       text: { en: 'Departments Delete',      tr: 'Departmanlar Silme' },            group: { en: 'Departments', tr: 'Departmanlar' } },
    { code: 'departmentmanageview',   text: { en: 'Departments Manage View', tr: 'Departmanlar Görünüm Ayarlama' }, group: { en: 'Departments', tr: 'Departmanlar' } },
    { code: 'departmentgetreport',    text: { en: 'Departments Get Report',  tr: 'Departmanlar Rapor Alma' },       group: { en: 'Departments', tr: 'Departmanlar' } },
    { code: 'departmentnotification', text: { en: 'Departments Notification',tr: 'Departmanlar Bildirim Alma' },    group: { en: 'Departments', tr: 'Departmanlar' } },
    
    { code: 'floorscreen',       text: { en: 'Floors Screen',      tr: 'Katlar Veri' },             group: { en: 'Floors', tr: 'Katlar' } },
    { code: 'floorview',         text: { en: 'Floors View',        tr: 'Katlar Görüntüleme' },      group: { en: 'Floors', tr: 'Katlar' } },
    { code: 'flooradd',          text: { en: 'Floors Add',         tr: 'Katlar Oluşturma' },        group: { en: 'Floors', tr: 'Katlar' } },
    { code: 'floorupdate',       text: { en: 'Floors Update',      tr: 'Katlar Güncelleme' },       group: { en: 'Floors', tr: 'Katlar' } },
    { code: 'floordelete',       text: { en: 'Floors Delete',      tr: 'Katlar Silme' },            group: { en: 'Floors', tr: 'Katlar' } },
    { code: 'floormanageview',   text: { en: 'Floors Manage View', tr: 'Katlar Görünüm Ayarlama' }, group: { en: 'Floors', tr: 'Katlar' } },
    { code: 'floorgetreport',    text: { en: 'Floors Get Report',  tr: 'Katlar Rapor Alma' },       group: { en: 'Floors', tr: 'Katlar' } },
    { code: 'floornotification', text: { en: 'Floors Notification',tr: 'Katlar Bildirim Alma' },    group: { en: 'Floors', tr: 'Katlar' } },
    
    { code: 'patienttypescreen',       text: { en: 'Patienttypes Screen',      tr: 'Hasta Türleri Veri' },             group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    { code: 'patienttypeview',         text: { en: 'Patienttypes View',        tr: 'Hasta Türleri Görüntüleme' },      group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    { code: 'patienttypeadd',          text: { en: 'Patienttypes Add',         tr: 'Hasta Türleri Oluşturma' },        group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    { code: 'patienttypeupdate',       text: { en: 'Patienttypes Update',      tr: 'Hasta Türleri Güncelleme' },       group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    { code: 'patienttypedelete',       text: { en: 'Patienttypes Delete',      tr: 'Hasta Türleri Silme' },            group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    { code: 'patienttypemanageview',   text: { en: 'Patienttypes Manage View', tr: 'Hasta Türleri Görünüm Ayarlama' }, group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    { code: 'patienttypegetreport',    text: { en: 'Patienttypes Get Report',  tr: 'Hasta Türleri Rapor Alma' },       group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    { code: 'patienttypenotification', text: { en: 'Patienttypes Notification',tr: 'Hasta Türleri Bildirim Alma' },    group: { en: 'Patienttypes', tr: 'Hasta Türleri' } },
    
    { code: 'periodscreen',       text: { en: 'Periods Screen',      tr: 'Periyotlar Veri' },             group: { en: 'Periods', tr: 'Periyotlar' } },
    { code: 'periodview',         text: { en: 'Periods View',        tr: 'Periyotlar Görüntüleme' },      group: { en: 'Periods', tr: 'Periyotlar' } },
    { code: 'periodadd',          text: { en: 'Periods Add',         tr: 'Periyotlar Oluşturma' },        group: { en: 'Periods', tr: 'Periyotlar' } },
    { code: 'periodupdate',       text: { en: 'Periods Update',      tr: 'Periyotlar Güncelleme' },       group: { en: 'Periods', tr: 'Periyotlar' } },
    { code: 'perioddelete',       text: { en: 'Periods Delete',      tr: 'Periyotlar Silme' },            group: { en: 'Periods', tr: 'Periyotlar' } },
    { code: 'periodmanageview',   text: { en: 'Periods Manage View', tr: 'Periyotlar Görünüm Ayarlama' }, group: { en: 'Periods', tr: 'Periyotlar' } },
    { code: 'periodgetreport',    text: { en: 'Periods Get Report',  tr: 'Periyotlar Rapor Alma' },       group: { en: 'Periods', tr: 'Periyotlar' } },
    { code: 'periodnotification', text: { en: 'Periods Notification',tr: 'Periyotlar Bildirim Alma' },    group: { en: 'Periods', tr: 'Periyotlar' } },
    
    { code: 'roomscreen',       text: { en: 'Rooms Screen',      tr: 'Odalar Veri' },             group: { en: 'Rooms', tr: 'Odalar' } },
    { code: 'roomview',         text: { en: 'Rooms View',        tr: 'Odalar Görüntüleme' },      group: { en: 'Rooms', tr: 'Odalar' } },
    { code: 'roomadd',          text: { en: 'Rooms Add',         tr: 'Odalar Oluşturma' },        group: { en: 'Rooms', tr: 'Odalar' } },
    { code: 'roomupdate',       text: { en: 'Rooms Update',      tr: 'Odalar Güncelleme' },       group: { en: 'Rooms', tr: 'Odalar' } },
    { code: 'roomdelete',       text: { en: 'Rooms Delete',      tr: 'Odalar Silme' },            group: { en: 'Rooms', tr: 'Odalar' } },
    { code: 'roommanageview',   text: { en: 'Rooms Manage View', tr: 'Odalar Görünüm Ayarlama' }, group: { en: 'Rooms', tr: 'Odalar' } },
    { code: 'roomgetreport',    text: { en: 'Rooms Get Report',  tr: 'Odalar Rapor Alma' },       group: { en: 'Rooms', tr: 'Odalar' } },
    { code: 'roomnotification', text: { en: 'Rooms Notification',tr: 'Odalar Bildirim Alma' },    group: { en: 'Rooms', tr: 'Odalar' } },
    
    { code: 'shiftdefinescreen',       text: { en: 'Shiftdefines Screen',      tr: 'Vardiya Tanımları Veri' },             group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    { code: 'shiftdefineview',         text: { en: 'Shiftdefines View',        tr: 'Vardiya Tanımları Görüntüleme' },      group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    { code: 'shiftdefineadd',          text: { en: 'Shiftdefines Add',         tr: 'Vardiya Tanımları Oluşturma' },        group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    { code: 'shiftdefineupdate',       text: { en: 'Shiftdefines Update',      tr: 'Vardiya Tanımları Güncelleme' },       group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    { code: 'shiftdefinedelete',       text: { en: 'Shiftdefines Delete',      tr: 'Vardiya Tanımları Silme' },            group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    { code: 'shiftdefinemanageview',   text: { en: 'Shiftdefines Manage View', tr: 'Vardiya Tanımları Görünüm Ayarlama' }, group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    { code: 'shiftdefinegetreport',    text: { en: 'Shiftdefines Get Report',  tr: 'Vardiya Tanımları Rapor Alma' },       group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    { code: 'shiftdefinenotification', text: { en: 'Shiftdefines Notification',tr: 'Vardiya Tanımları Bildirim Alma' },    group: { en: 'Shiftdefines', tr: 'Vardiya Tanımları' } },
    
    { code: 'tododefinescreen',       text: { en: 'Routines Screen',      tr: 'Rutinler Veri' },             group: { en: 'Routines', tr: 'Rutinler' } },
    { code: 'tododefineview',         text: { en: 'Routines View',        tr: 'Rutinler Görüntüleme' },      group: { en: 'Routines', tr: 'Rutinler' } },
    { code: 'tododefineadd',          text: { en: 'Routines Add',         tr: 'Rutinler Oluşturma' },        group: { en: 'Routines', tr: 'Rutinler' } },
    { code: 'tododefineupdate',       text: { en: 'Routines Update',      tr: 'Rutinler Güncelleme' },       group: { en: 'Routines', tr: 'Rutinler' } },
    { code: 'tododefinedelete',       text: { en: 'Routines Delete',      tr: 'Rutinler Silme' },            group: { en: 'Routines', tr: 'Rutinler' } },
    { code: 'tododefinemanageview',   text: { en: 'Routines Manage View', tr: 'Rutinler Görünüm Ayarlama' }, group: { en: 'Routines', tr: 'Rutinler' } },
    { code: 'tododefinegetreport',    text: { en: 'Routines Get Report',  tr: 'Rutinler Rapor Alma' },       group: { en: 'Routines', tr: 'Rutinler' } },
    { code: 'tododefinenotification', text: { en: 'Routines Notification',tr: 'Rutinler Bildirim Alma' },    group: { en: 'Routines', tr: 'Rutinler' } },
    
    { code: 'todogroupdefinescreen',       text: { en: 'Routine Lists Screen',      tr: 'Rutin Listeleri Veri' },             group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    { code: 'todogroupdefineview',         text: { en: 'Routine Lists View',        tr: 'Rutin Listeleri Görüntüleme' },      group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    { code: 'todogroupdefineadd',          text: { en: 'Routine Lists Add',         tr: 'Rutin Listeleri Oluşturma' },        group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    { code: 'todogroupdefineupdate',       text: { en: 'Routine Lists Update',      tr: 'Rutin Listeleri Güncelleme' },       group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    { code: 'todogroupdefinedelete',       text: { en: 'Routine Lists Delete',      tr: 'Rutin Listeleri Silme' },            group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    { code: 'todogroupdefinemanageview',   text: { en: 'Routine Lists Manage View', tr: 'Rutin Listeleri Görünüm Ayarlama' }, group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    { code: 'todogroupdefinegetreport',    text: { en: 'Routine Lists Get Report',  tr: 'Rutin Listeleri Rapor Alma' },       group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    { code: 'todogroupdefinenotification', text: { en: 'Routine Lists Notification',tr: 'Rutin Listeleri Bildirim Alma' },    group: { en: 'Routine Lists', tr: 'Rutin Listeleri' } },
    
    { code: 'unitscreen',       text: { en: 'Units Screen',      tr: 'Birimler Veri' },             group: { en: 'Units', tr: 'Birimler' } },
    { code: 'unitview',         text: { en: 'Units View',        tr: 'Birimler Görüntüleme' },      group: { en: 'Units', tr: 'Birimler' } },
    { code: 'unitadd',          text: { en: 'Units Add',         tr: 'Birimler Oluşturma' },        group: { en: 'Units', tr: 'Birimler' } },
    { code: 'unitupdate',       text: { en: 'Units Update',      tr: 'Birimler Güncelleme' },       group: { en: 'Units', tr: 'Birimler' } },
    { code: 'unitdelete',       text: { en: 'Units Delete',      tr: 'Birimler Silme' },            group: { en: 'Units', tr: 'Birimler' } },
    { code: 'unitmanageview',   text: { en: 'Units Manage View', tr: 'Birimler Görünüm Ayarlama' }, group: { en: 'Units', tr: 'Birimler' } },
    { code: 'unitgetreport',    text: { en: 'Units Get Report',  tr: 'Birimler Rapor Alma' },       group: { en: 'Units', tr: 'Birimler' } },
    { code: 'unitnotification', text: { en: 'Units Notification',tr: 'Birimler Bildirim Alma' },    group: { en: 'Units', tr: 'Birimler' } },
    
    { code: 'mailsettingscreen',       text: { en: 'Mailsettings Screen',      tr: 'Mail Ayarları Veri' },             group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingview',         text: { en: 'Mailsettings View',        tr: 'Mail Ayarları Görüntüleme' },      group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingadd',          text: { en: 'Mailsettings Add',         tr: 'Mail Ayarları Oluşturma' },        group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingupdate',       text: { en: 'Mailsettings Update',      tr: 'Mail Ayarları Güncelleme' },       group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingdelete',       text: { en: 'Mailsettings Delete',      tr: 'Mail Ayarları Silme' },            group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingmanageview',   text: { en: 'Mailsettings Manage View', tr: 'Mail Ayarları Görünüm Ayarlama' }, group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettinggetreport',    text: { en: 'Mailsettings Get Report',  tr: 'Mail Ayarları Rapor Alma' },       group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    { code: 'mailsettingnotification', text: { en: 'Mailsettings Notification',tr: 'Mail Ayarları Bildirim Alma' },    group: { en: 'Mailsettings', tr: 'Mail Ayarları' } },
    
    { code: 'printtemplatescreen',       text: { en: 'Printtemplates Screen',      tr: 'Yazdırma Taslakları Veri' },             group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    { code: 'printtemplateview',         text: { en: 'Printtemplates View',        tr: 'Yazdırma Taslakları Görüntüleme' },      group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    { code: 'printtemplateadd',          text: { en: 'Printtemplates Add',         tr: 'Yazdırma Taslakları Oluşturma' },        group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    { code: 'printtemplateupdate',       text: { en: 'Printtemplates Update',      tr: 'Yazdırma Taslakları Güncelleme' },       group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    { code: 'printtemplatedelete',       text: { en: 'Printtemplates Delete',      tr: 'Yazdırma Taslakları Silme' },            group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    { code: 'printtemplatemanageview',   text: { en: 'Printtemplates Manage View', tr: 'Yazdırma Taslakları Görünüm Ayarlama' }, group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    { code: 'printtemplategetreport',    text: { en: 'Printtemplates Get Report',  tr: 'Yazdırma Taslakları Rapor Alma' },       group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    { code: 'printtemplatenotification', text: { en: 'Printtemplates Notification',tr: 'Yazdırma Taslakları Bildirim Alma' },    group: { en: 'Printtemplates', tr: 'Yazdırma Taslakları' } },
    
    { code: 'rulescreen',       text: { en: 'Rules Screen',      tr: 'Kurallar Veri' },             group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleview',         text: { en: 'Rules View',        tr: 'Kurallar Görüntüleme' },      group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleadd',          text: { en: 'Rules Add',         tr: 'Kurallar Oluşturma' },        group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruleupdate',       text: { en: 'Rules Update',      tr: 'Kurallar Güncelleme' },       group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'ruledelete',       text: { en: 'Rules Delete',      tr: 'Kurallar Silme' },            group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'rulemanageview',   text: { en: 'Rules Manage View', tr: 'Kurallar Görünüm Ayarlama' }, group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'rulegetreport',    text: { en: 'Rules Get Report',  tr: 'Kurallar Rapor Alma' },       group: { en: 'Rules', tr: 'Kurallar' } },
    { code: 'rulenotification', text: { en: 'Rules Notification',tr: 'Kurallar Bildirim Alma' },    group: { en: 'Rules', tr: 'Kurallar' } },

    { code: 'purchaseorderscreen',       text: { en: 'Purchaseorders Screen',      tr: 'Satın Almalar Veri' },             group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseorderview',         text: { en: 'Purchaseorders View',        tr: 'Satın Almalar Görüntüleme' },      group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseorderadd',          text: { en: 'Purchaseorders Add',         tr: 'Satın Almalar Oluşturma' },        group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseorderupdate',       text: { en: 'Purchaseorders Update',      tr: 'Satın Almalar Güncelleme' },       group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseordercheck',        text: { en: 'Purchaseorders Check',       tr: 'Satın Almalar Kontrol Etme' },     group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseorderapprove',      text: { en: 'Purchaseorders Approve',     tr: 'Satın Almalar Onaylama' },         group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseordercomplete',     text: { en: 'Purchaseorders Complete',    tr: 'Satın Almalar Tamamlama' },        group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseorderdelete',       text: { en: 'Purchaseorders Delete',      tr: 'Satın Almalar Silme' },            group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseordermanageview',   text: { en: 'Purchaseorders Manage View', tr: 'Satın Almalar Görünüm Ayarlama' }, group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseordergetreport',    text: { en: 'Purchaseorders Get Report',  tr: 'Satın Almalar Rapor Alma' },       group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    { code: 'purchaseordernotification', text: { en: 'Purchaseorders Notification',tr: 'Satın Almalar Bildirim Alma' },    group: { en: 'Purchaseorders', tr: 'Satın Almalar' } },
    
    { code: 'stockscreen',       text: { en: 'Stocks Screen',      tr: 'Stoklar Veri' },             group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stockview',         text: { en: 'Stocks View',        tr: 'Stoklar Görüntüleme' },      group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stockadd',          text: { en: 'Stocks Add',         tr: 'Stoklar Oluşturma' },        group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stockupdate',       text: { en: 'Stocks Update',      tr: 'Stoklar Güncelleme' },       group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stockapprove',      text: { en: 'Stocks Approve',     tr: 'Stoklar Onaylama' },         group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stockdelete',       text: { en: 'Stocks Delete',      tr: 'Stoklar Silme' },            group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stockmanageview',   text: { en: 'Stocks Manage View', tr: 'Stoklar Görünüm Ayarlama' }, group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stockgetreport',    text: { en: 'Stocks Get Report',  tr: 'Stoklar Rapor Alma' },       group: { en: 'Stocks', tr: 'Stoklar' } },
    { code: 'stocknotification', text: { en: 'Stocks Notification',tr: 'Stoklar Bildirim Alma' },    group: { en: 'Stocks', tr: 'Stoklar' } },
    
    { code: 'stockdefinescreen',       text: { en: 'Stockdefines Screen',      tr: 'Stok Tanımları Veri' },             group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    { code: 'stockdefineview',         text: { en: 'Stockdefines View',        tr: 'Stok Tanımları Görüntüleme' },      group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    { code: 'stockdefineadd',          text: { en: 'Stockdefines Add',         tr: 'Stok Tanımları Oluşturma' },        group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    { code: 'stockdefineupdate',       text: { en: 'Stockdefines Update',      tr: 'Stok Tanımları Güncelleme' },       group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    { code: 'stockdefinedelete',       text: { en: 'Stockdefines Delete',      tr: 'Stok Tanımları Silme' },            group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    { code: 'stockdefinemanageview',   text: { en: 'Stockdefines Manage View', tr: 'Stok Tanımları Görünüm Ayarlama' }, group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    { code: 'stockdefinegetreport',    text: { en: 'Stockdefines Get Report',  tr: 'Stok Tanımları Rapor Alma' },       group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    { code: 'stockdefinenotification', text: { en: 'Stockdefines Notification',tr: 'Stok Tanımları Bildirim Alma' },    group: { en: 'Stockdefines', tr: 'Stok Tanımları' } },
    
    { code: 'stockmovementscreen',       text: { en: 'Stockmovements Screen',      tr: 'Stok Hareketleri Veri' },             group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementview',         text: { en: 'Stockmovements View',        tr: 'Stok Hareketleri Görüntüleme' },      group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementadd',          text: { en: 'Stockmovements Add',         tr: 'Stok Hareketleri Oluşturma' },        group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementupdate',       text: { en: 'Stockmovements Update',      tr: 'Stok Hareketleri Güncelleme' },       group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementapprove',      text: { en: 'Stockmovements Approve',     tr: 'Stok Hareketleri Onaylama' },         group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementdelete',       text: { en: 'Stockmovements Delete',      tr: 'Stok Hareketleri Silme' },            group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementmanageview',   text: { en: 'Stockmovements Manage View', tr: 'Stok Hareketleri Görünüm Ayarlama' }, group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementgetreport',    text: { en: 'Stockmovements Get Report',  tr: 'Stok Hareketleri Rapor Alma' },       group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    { code: 'stockmovementnotification', text: { en: 'Stockmovements Notification',tr: 'Stok Hareketleri Bildirim Alma' },    group: { en: 'Stockmovements', tr: 'Stok Hareketleri' } },
    
    { code: 'warehousescreen',       text: { en: 'Warehouses Screen',      tr: 'Ambarlar Veri' },             group: { en: 'Warehouses', tr: 'Ambarlar' } },
    { code: 'warehouseview',         text: { en: 'Warehouses View',        tr: 'Ambarlar Görüntüleme' },      group: { en: 'Warehouses', tr: 'Ambarlar' } },
    { code: 'warehouseadd',          text: { en: 'Warehouses Add',         tr: 'Ambarlar Oluşturma' },        group: { en: 'Warehouses', tr: 'Ambarlar' } },
    { code: 'warehouseupdate',       text: { en: 'Warehouses Update',      tr: 'Ambarlar Güncelleme' },       group: { en: 'Warehouses', tr: 'Ambarlar' } },
    { code: 'warehousedelete',       text: { en: 'Warehouses Delete',      tr: 'Ambarlar Silme' },            group: { en: 'Warehouses', tr: 'Ambarlar' } },
    { code: 'warehousemanageview',   text: { en: 'Warehouses Manage View', tr: 'Ambarlar Görünüm Ayarlama' }, group: { en: 'Warehouses', tr: 'Ambarlar' } },
    { code: 'warehousegetreport',    text: { en: 'Warehouses Get Report',  tr: 'Ambarlar Rapor Alma' },       group: { en: 'Warehouses', tr: 'Ambarlar' } },
    { code: 'warehousenotification', text: { en: 'Warehouses Notification',tr: 'Ambarlar Bildirim Alma' },    group: { en: 'Warehouses', tr: 'Ambarlar' } },
    
    { code: 'equipmentgroupscreen',       text: { en: 'Equipmentgroups Screen',      tr: 'Ekipman Grupları Veri' },             group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    { code: 'equipmentgroupview',         text: { en: 'Equipmentgroups View',        tr: 'Ekipman Grupları Görüntüleme' },      group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    { code: 'equipmentgroupadd',          text: { en: 'Equipmentgroups Add',         tr: 'Ekipman Grupları Oluşturma' },        group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    { code: 'equipmentgroupupdate',       text: { en: 'Equipmentgroups Update',      tr: 'Ekipman Grupları Güncelleme' },       group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    { code: 'equipmentgroupdelete',       text: { en: 'Equipmentgroups Delete',      tr: 'Ekipman Grupları Silme' },            group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    { code: 'equipmentgroupmanageview',   text: { en: 'Equipmentgroups Manage View', tr: 'Ekipman Grupları Görünüm Ayarlama' }, group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    { code: 'equipmentgroupgetreport',    text: { en: 'Equipmentgroups Get Report',  tr: 'Ekipman Grupları Rapor Alma' },       group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    { code: 'equipmentgroupnotification', text: { en: 'Equipmentgroups Notification',tr: 'Ekipman Grupları Bildirim Alma' },    group: { en: 'Equipmentgroups', tr: 'Ekipman Grupları' } },
    
    { code: 'equipmentscreen',       text: { en: 'Equipments Screen',      tr: 'Ekipmanlar Veri' },             group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    { code: 'equipmentview',         text: { en: 'Equipments View',        tr: 'Ekipmanlar Görüntüleme' },      group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    { code: 'equipmentadd',          text: { en: 'Equipments Add',         tr: 'Ekipmanlar Oluşturma' },        group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    { code: 'equipmentupdate',       text: { en: 'Equipments Update',      tr: 'Ekipmanlar Güncelleme' },       group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    { code: 'equipmentdelete',       text: { en: 'Equipments Delete',      tr: 'Ekipmanlar Silme' },            group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    { code: 'equipmentmanageview',   text: { en: 'Equipments Manage View', tr: 'Ekipmanlar Görünüm Ayarlama' }, group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    { code: 'equipmentgetreport',    text: { en: 'Equipments Get Report',  tr: 'Ekipmanlar Rapor Alma' },       group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    { code: 'equipmentnotification', text: { en: 'Equipments Notification',tr: 'Ekipmanlar Bildirim Alma' },    group: { en: 'Equipments', tr: 'Ekipmanlar' } },
    
    { code: 'userscreen',         text: { en: 'Users Screen',           tr: 'Kullanıcılar Veri' },               group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userview',           text: { en: 'Users View',             tr: 'Kullanıcılar Görüntüleme' },        group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'useradd',            text: { en: 'Users Add',              tr: 'Kullanıcılar Oluşturma' },          group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdate',         text: { en: 'Users Update',           tr: 'Kullanıcılar Güncelleme' },         group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userremove',         text: { en: 'Users Remove',           tr: 'Kullanıcılar Kurumdan Çıkartma' },  group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdatecase',     text: { en: 'Users Update Case',      tr: 'Kullanıcılar Durum Güncelleme' },   group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userupdatemovement', text: { en: 'Users Update Movement',  tr: 'Kullanıcılar Hareket Güncelleme' }, group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userdeletemovement', text: { en: 'Users Delete Movement',  tr: 'Kullanıcılar Hareket Silme' },      group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'userdelete',         text: { en: 'Users Delete',           tr: 'Kullanıcılar Silme' },              group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'usermanageview',     text: { en: 'Users Manage View',      tr: 'Kullanıcılar Görünüm Ayarlama' },   group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'usergetreport',      text: { en: 'Users Get Report',       tr: 'Kullanıcılar Rapor Alma' },         group: { en: 'Users', tr: 'Kullanıcılar' } },
    { code: 'usernotification',   text: { en: 'Users Notification',     tr: 'Kullanıcılar Bildirim Alma' },      group: { en: 'Users', tr: 'Kullanıcılar' } },
    
    { code: 'filescreen',       text: { en: 'Files Screen',      tr: 'Dosyalar Veri' },             group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'fileview',         text: { en: 'Files View',        tr: 'Dosyalar Görüntüleme' },      group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'fileadd',          text: { en: 'Files Add',         tr: 'Dosyalar Oluşturma' },        group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'fileupdate',       text: { en: 'Files Update',      tr: 'Dosyalar Güncelleme' },       group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'filedelete',       text: { en: 'Files Delete',      tr: 'Dosyalar Silme' },            group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'filedownload',     text: { en: 'Files Download',    tr: 'Dosyalar İndirme' },          group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'filemanageview',   text: { en: 'Files Manage View', tr: 'Dosyalar Görünüm Ayarlama' }, group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'filegetreport',    text: { en: 'Files Get Report',  tr: 'Dosyalar Rapor Alma' },       group: { en: 'Files', tr: 'Dosyalar' } },
    { code: 'filenotification', text: { en: 'Files Notification',tr: 'Dosyalar Bildirim Alma' },    group: { en: 'Files', tr: 'Dosyalar' } },
 
    { code: 'preregistrationview',         text: { en: 'Preregistration View',        tr: 'Ön Kayıtlar Görüntüleme' },      group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationadd',          text: { en: 'Preregistration Add',         tr: 'Ön Kayıtlar Oluşturma' },        group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationupdate',       text: { en: 'Preregistrations Update',     tr: 'Ön Kayıtlar Güncelleme' },       group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationcheck',        text: { en: 'Preregistration Check',       tr: 'Ön Kayıtlar Oluşturma' },        group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationapprove',      text: { en: 'Preregistration Approve',     tr: 'Ön Kayıtlar Oluşturma' },        group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationcomplete',     text: { en: 'Preregistration Complete',    tr: 'Ön Kayıtlar Oluşturma' },        group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationdelete',       text: { en: 'Preregistrations Delete',      tr: 'Ön Kayıtlar Silme' },            group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationmanageview',   text: { en: 'Preregistration Manage View', tr: 'Ön Kayıtlar Görünüm Ayarlama' }, group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    { code: 'preregistrationgetreport',    text: { en: 'Preregistration Get Report',  tr: 'Ön Kayıtlar Rapor Alma' },       group: { en: 'Preregistrations', tr: 'Ön Kayıtlar' } },
    
    { code: 'patientscreen',       text: { en: 'Patients Screen',      tr: 'Hastalar Veri' },             group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientview',         text: { en: 'Patients View',        tr: 'Hastalar Görüntüleme' },      group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientupdate',       text: { en: 'Patients Update',      tr: 'Hastalar Güncelleme' },       group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientupdatecase',   text: { en: 'Patients Update',      tr: 'Hastalar Güncelleme' },       group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientupdateplace',  text: { en: 'Patients Update',      tr: 'Hastalar Güncelleme' },       group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientdelete',       text: { en: 'Patients Delete',      tr: 'Hastalar Silme' },            group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientmanageview',   text: { en: 'Patients Manage View', tr: 'Hastalar Görünüm Ayarlama' }, group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientgetreport',    text: { en: 'Patients Get Report',  tr: 'Hastalar Rapor Alma' },       group: { en: 'Patients', tr: 'Hastalar' } },
    { code: 'patientnotification', text: { en: 'Patients Notification',tr: 'Hastalar Bildirim Alma' },    group: { en: 'Patients', tr: 'Hastalar' } },
    
    { code: 'placeviewview',              text: { en: 'Placeviews View',                tr: 'Hasta Yerleşimleri Görüntüleme' },        group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'overviewview',               text: { en: 'Overview View',                  tr: 'Hasta Grafikleri Görüntüleme' },          group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'patientsrollcallview',       text: { en: 'Patient Roll Call View',         tr: 'Hasta Yoklamaları Görüntüleme' },         group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'overviewcardview',           text: { en: 'Overview Card View',             tr: 'Gösterge Kartları Görüntüleme' },         group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'overviewhealthcarecardview', text: { en: 'Overview Health Care Card View', tr: 'Bakım Hizmetleri Kartları Görüntüleme' }, group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'companyfileview',            text: { en: 'Company Files View',             tr: 'Kurum Dosya Arşivi Görüntüleme' },        group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'approveview',                text: { en: 'Approve Page View',              tr: 'Onay Bekleyen İşlemler Görüntüleme' },    group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
    { code: 'patientfollowupview',        text: { en: 'Patient Followup Page View',     tr: 'Genel Hasta Takibi Görüntüleme' },        group: { en: 'Organization Management', tr: 'Kurum Yönetimi' } },
     
    { code: 'patientdefinescreen',       text: { en: 'Patientdefines Screen',      tr: 'Hasta Tanımları Veri' },             group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    { code: 'patientdefineview',         text: { en: 'Patientdefines View',        tr: 'Hasta Tanımları Görüntüleme' },      group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    { code: 'patientdefineadd',          text: { en: 'Patientdefines Add',         tr: 'Hasta Tanımları Oluşturma' },        group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    { code: 'patientdefineupdate',       text: { en: 'Patientdefines Update',      tr: 'Hasta Tanımları Güncelleme' },       group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    { code: 'patientdefinedelete',       text: { en: 'Patientdefines Delete',      tr: 'Hasta Tanımları Silme' },            group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    { code: 'patientdefinemanageview',   text: { en: 'Patientdefines Manage View', tr: 'Hasta Tanımları Görünüm Ayarlama' }, group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    { code: 'patientdefinegetreport',    text: { en: 'Patientdefines Get Report',  tr: 'Hasta Tanımları Rapor Alma' },       group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    { code: 'patientdefinenotification', text: { en: 'Patientdefines Notification',tr: 'Hasta Tanımları Bildirim Alma' },    group: { en: 'Patientdefines', tr: 'Hasta Tanımları' } },
    
    { code: 'breakdownscreen',       text: { en: 'Breakdowns Screen',      tr: 'Arıza Talepleri Veri' },             group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdownview',         text: { en: 'Breakdowns View',        tr: 'Arıza Talepleri Görüntüleme' },      group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdownadd',          text: { en: 'Breakdowns Add',         tr: 'Arıza Talepleri Oluşturma' },        group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdownupdate',       text: { en: 'Breakdowns Update',      tr: 'Arıza Talepleri Güncelleme' },       group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdowncomplete',     text: { en: 'Breakdowns Complete',    tr: 'Arıza Talepleri Tamamlama' },        group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdowndelete',       text: { en: 'Breakdowns Delete',      tr: 'Arıza Talepleri Silme' },            group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdownmanageview',   text: { en: 'Breakdowns Manage View', tr: 'Arıza Talepleri Görünüm Ayarlama' }, group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdowngetreport',    text: { en: 'Breakdowns Get Report',  tr: 'Arıza Talepleri Rapor Alma' },       group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    { code: 'breakdownnotification', text: { en: 'Breakdowns Notification',tr: 'Arıza Talepleri Bildirim Alma' },    group: { en: 'Breakdowns', tr: 'Arıza Talepleri' } },
    
    { code: 'mainteancescreen',       text: { en: 'Mainteances Screen',      tr: 'Bakım Talepleri Veri' },             group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteanceview',         text: { en: 'Mainteances View',        tr: 'Bakım Talepleri Görüntüleme' },      group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteanceadd',          text: { en: 'Mainteances Add',         tr: 'Bakım Talepleri Oluşturma' },        group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteanceupdate',       text: { en: 'Mainteances Update',      tr: 'Bakım Talepleri Güncelleme' },       group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteancecomplete',     text: { en: 'Mainteances Complete',    tr: 'Bakım Talepleri Tamamlama' },        group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteancedelete',       text: { en: 'Mainteances Delete',      tr: 'Bakım Talepleri Silme' },            group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteancemanageview',   text: { en: 'Mainteances Manage View', tr: 'Bakım Talepleri Görünüm Ayarlama' }, group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteancegetreport',    text: { en: 'Mainteances Get Report',  tr: 'Bakım Talepleri Rapor Alma' },       group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    { code: 'mainteancenotification', text: { en: 'Mainteances Notification',tr: 'Bakım Talepleri Bildirim Alma' },    group: { en: 'Mainteances', tr: 'Bakım Talepleri' } },
    
    { code: 'patientcashregisterscreen',       text: { en: 'Patientcashregisters Screen',      tr: 'Hasta Para Türleri Veri' },             group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    { code: 'patientcashregisterview',         text: { en: 'Patientcashregisters View',        tr: 'Hasta Para Türleri Görüntüleme' },      group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    { code: 'patientcashregisteradd',          text: { en: 'Patientcashregisters Add',         tr: 'Hasta Para Türleri Oluşturma' },        group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    { code: 'patientcashregisterupdate',       text: { en: 'Patientcashregisters Update',      tr: 'Hasta Para Türleri Güncelleme' },       group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    { code: 'patientcashregisterdelete',       text: { en: 'Patientcashregisters Delete',      tr: 'Hasta Para Türleri Silme' },            group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    { code: 'patientcashregistermanageview',   text: { en: 'Patientcashregisters Manage View', tr: 'Hasta Para Türleri Görünüm Ayarlama' }, group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    { code: 'patientcashregistergetreport',    text: { en: 'Patientcashregisters Get Report',  tr: 'Hasta Para Türleri Rapor Alma' },       group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    { code: 'patientcashregisternotification', text: { en: 'Patientcashregisters Notification',tr: 'Hasta Para Türleri Bildirim Alma' },    group: { en: 'Patientcashregisters', tr: 'Hasta Para Türleri' } },
    
    { code: 'patientcashmovementscreen',       text: { en: 'Patientcashmovements Screen',      tr: 'Hasta Cüzdanı Veri' },             group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    { code: 'patientcashmovementview',         text: { en: 'Patientcashmovements View',        tr: 'Hasta Cüzdanı Görüntüleme' },      group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    { code: 'patientcashmovementadd',          text: { en: 'Patientcashmovements Add',         tr: 'Hasta Cüzdanı Oluşturma' },        group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    { code: 'patientcashmovementupdate',       text: { en: 'Patientcashmovements Update',      tr: 'Hasta Cüzdanı Güncelleme' },       group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    { code: 'patientcashmovementdelete',       text: { en: 'Patientcashmovements Delete',      tr: 'Hasta Cüzdanı Silme' },            group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    { code: 'patientcashmovementmanageview',   text: { en: 'Patientcashmovements Manage View', tr: 'Hasta Cüzdanı Görünüm Ayarlama' }, group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    { code: 'patientcashmovementgetreport',    text: { en: 'Patientcashmovements Get Report',  tr: 'Hasta Cüzdanı Rapor Alma' },       group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    { code: 'patientcashmovementnotification', text: { en: 'Patientcashmovements Notification',tr: 'Hasta Cüzdanı Bildirim Alma' },    group: { en: 'Patientcashmovements', tr: 'Hasta Cüzdanı' } },
    
    { code: 'companycashmovementscreen',       text: { en: 'Companycashmovements Screen',      tr: 'Kurum cüzdanı Veri' },             group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    { code: 'companycashmovementview',         text: { en: 'Companycashmovements View',        tr: 'Kurum cüzdanı Görüntüleme' },      group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    { code: 'companycashmovementadd',          text: { en: 'Companycashmovements Add',         tr: 'Kurum cüzdanı Oluşturma' },        group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    { code: 'companycashmovementupdate',       text: { en: 'Companycashmovements Update',      tr: 'Kurum cüzdanı Güncelleme' },       group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    { code: 'companycashmovementdelete',       text: { en: 'Companycashmovements Delete',      tr: 'Kurum cüzdanı Silme' },            group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    { code: 'companycashmovementmanageview',   text: { en: 'Companycashmovements Manage View', tr: 'Kurum cüzdanı Görünüm Ayarlama' }, group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    { code: 'companycashmovementgetreport',    text: { en: 'Companycashmovements Get Report',  tr: 'Kurum cüzdanı Rapor Alma' },       group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    { code: 'companycashmovementnotification', text: { en: 'Companycashmovements Notification',tr: 'Kurum cüzdanı Bildirim Alma' },    group: { en: 'Companycashmovements', tr: 'Kurum Cüzdanı' } },
    
    { code: 'usagetypescreen',       text: { en: 'Usagetypes Screen',      tr: 'Kullanım Türleri Veri' },             group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    { code: 'usagetypeview',         text: { en: 'Usagetypes View',        tr: 'Kullanım Türleri Görüntüleme' },      group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    { code: 'usagetypeadd',          text: { en: 'Usagetypes Add',         tr: 'Kullanım Türleri Oluşturma' },        group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    { code: 'usagetypeupdate',       text: { en: 'Usagetypes Update',      tr: 'Kullanım Türleri Güncelleme' },       group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    { code: 'usagetypedelete',       text: { en: 'Usagetypes Delete',      tr: 'Kullanım Türleri Silme' },            group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    { code: 'usagetypemanageview',   text: { en: 'Usagetypes Manage View', tr: 'Kullanım Türleri Görünüm Ayarlama' }, group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    { code: 'usagetypegetreport',    text: { en: 'Usagetypes Get Report',  tr: 'Kullanım Türleri Rapor Alma' },       group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    { code: 'usagetypenotification', text: { en: 'Usagetypes Notification',tr: 'Kullanım Türleri Bildirim Alma' },    group: { en: 'Usagetypes', tr: 'Kullanım Türleri' } },
    
    { code: 'careplanparameterscreen',       text: { en: 'Careplan Parameter Screen',      tr: 'Bakım Planı Parametreleri Veri' },             group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    { code: 'careplanparameterview',         text: { en: 'Careplan Parameter View',        tr: 'Bakım Planı Parametreleri Görüntüleme' },      group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    { code: 'careplanparameteradd',          text: { en: 'Careplan Parameter Add',         tr: 'Bakım Planı Parametreleri Oluşturma' },        group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    { code: 'careplanparameterupdate',       text: { en: 'Careplan Parameter Update',      tr: 'Bakım Planı Parametreleri Güncelleme' },       group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    { code: 'careplanparameterdelete',       text: { en: 'Careplan Parameter Delete',      tr: 'Bakım Planı Parametreleri Silme' },            group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    { code: 'careplanparametermanageview',   text: { en: 'Careplan Parameter Manage View', tr: 'Bakım Planı Parametreleri Görünüm Ayarlama' }, group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    { code: 'careplanparametergetreport',    text: { en: 'Careplan Parameter Get Report',  tr: 'Bakım Planı Parametreleri Rapor Alma' },       group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    { code: 'careplanparameternotification', text: { en: 'Careplan Parameter Notification',tr: 'Bakım Planı Parametreleri Bildirim Alma' },    group: { en: 'Careplan Parameters', tr: 'Bakım Planı Parametreleri' } },
    
    { code: 'supportplanlistscreen',       text: { en: 'Supportplanlists Screen',       tr: 'Destek Plan Listeleri Veri' },             group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    { code: 'supportplanlistview',         text: { en: 'Supportplanlists View',         tr: 'Destek Plan Listeleri Görüntüleme' },      group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    { code: 'supportplanlistadd',          text: { en: 'Supportplanlists Add',          tr: 'Destek Plan Listeleri Oluşturma' },        group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    { code: 'supportplanlistupdate',       text: { en: 'Supportplanlists Update',       tr: 'Destek Plan Listeleri Güncelleme' },       group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    { code: 'supportplanlistdelete',       text: { en: 'Supportplanlists Delete',       tr: 'Destek Plan Listeleri Silme' },            group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    { code: 'supportplanlistmanageview',   text: { en: 'Supportplanlists Manage View',  tr: 'Destek Plan Listeleri Görünüm Ayarlama' }, group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    { code: 'supportplanlistgetreport',    text: { en: 'Supportplanlists Get Report',   tr: 'Destek Plan Listeleri Rapor Alma' },       group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    { code: 'supportplanlistnotification', text: { en: 'Supportplanlists Notification', tr: 'Destek Plan Listeleri Bildirim Alma' },    group: { en: 'Supportplanlists', tr: 'Destek Plan Listeleri' } },
    
    { code: 'supportplanscreen',       text: { en: 'Supportplans Screen',       tr: 'Destek Planları Veri' },             group: { en: 'Supportplans', tr: 'Destek Planları' } },
    { code: 'supportplanview',         text: { en: 'Supportplans View',         tr: 'Destek Planları Görüntüleme' },      group: { en: 'Supportplans', tr: 'Destek Planları' } },
    { code: 'supportplanadd',          text: { en: 'Supportplans Add',          tr: 'Destek Planları Oluşturma' },        group: { en: 'Supportplans', tr: 'Destek Planları' } },
    { code: 'supportplanupdate',       text: { en: 'Supportplans Update',       tr: 'Destek Planları Güncelleme' },       group: { en: 'Supportplans', tr: 'Destek Planları' } },
    { code: 'supportplandelete',       text: { en: 'Supportplans Delete',       tr: 'Destek Planları Silme' },            group: { en: 'Supportplans', tr: 'Destek Planları' } },
    { code: 'supportplanmanageview',   text: { en: 'Supportplans Manage View',  tr: 'Destek Planları Görünüm Ayarlama' }, group: { en: 'Supportplans', tr: 'Destek Planları' } },
    { code: 'supportplangetreport',    text: { en: 'Supportplans Get Report',   tr: 'Destek Planları Rapor Alma' },       group: { en: 'Supportplans', tr: 'Destek Planları' } },
    { code: 'supportplannotification', text: { en: 'Supportplans Notification', tr: 'Destek Planları Bildirim Alma' },    group: { en: 'Supportplans', tr: 'Destek Planları' } },
    
    { code: 'careplanscreen',          text: { en: 'Careplans Screen',       tr: 'Bireysel Bakım Planları Veri' },              group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplanview',            text: { en: 'Careplans View',         tr: 'Bireysel Bakım Planları Görüntüleme' },       group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplanadd',             text: { en: 'Careplans Add',          tr: 'Bireysel Bakım Planları Oluşturma' },         group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplanupdate',          text: { en: 'Careplans Update',       tr: 'Bireysel Bakım Planları Güncelleme' },        group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplansavepreview',     text: { en: 'Careplans Save Preview', tr: 'Bireysel Bakım Planları Taslak Kayıt Etme' }, group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplanapprove',         text: { en: 'Careplans Approve',      tr: 'Bireysel Bakım Planları Onaylama' },          group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplandelete',          text: { en: 'Careplans Delete',       tr: 'Bireysel Bakım Planları Silme' },             group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplanmanageview',      text: { en: 'Careplans Manage View',  tr: 'Bireysel Bakım Planları Görünüm Ayarlama' },  group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplangetreport',       text: { en: 'Careplans Get Report',   tr: 'Bireysel Bakım Planları Rapor Alma' },        group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    { code: 'careplannotification',    text: { en: 'Careplans Notification', tr: 'Bireysel Bakım Planları Bildirim Alma' },     group: { en: 'Careplans', tr: 'Bireysel Bakım Planları' } },
    
    { code: 'professionscreen',       text: { en: 'Professions Screen',      tr: 'Meslekler Veri' },             group: { en: 'Professions', tr: 'Meslekler' } },
    { code: 'professionview',         text: { en: 'Professions View',        tr: 'Meslekler Görüntüleme' },      group: { en: 'Professions', tr: 'Meslekler' } },
    { code: 'professionadd',          text: { en: 'Professions Add',         tr: 'Meslekler Oluşturma' },        group: { en: 'Professions', tr: 'Meslekler' } },
    { code: 'professionupdate',       text: { en: 'Professions Update',      tr: 'Meslekler Güncelleme' },       group: { en: 'Professions', tr: 'Meslekler' } },
    { code: 'professiondelete',       text: { en: 'Professions Delete',      tr: 'Meslekler Silme' },            group: { en: 'Professions', tr: 'Meslekler' } },
    { code: 'professionmanageview',   text: { en: 'Professions Manage View', tr: 'Meslekler Görünüm Ayarlama' }, group: { en: 'Professions', tr: 'Meslekler' } },
    { code: 'professiongetreport',    text: { en: 'Professions Get Report',  tr: 'Meslekler Rapor Alma' },       group: { en: 'Professions', tr: 'Meslekler' } },
    { code: 'professionnotification', text: { en: 'Professions Notification',tr: 'Meslekler Bildirim Alma' },    group: { en: 'Professions', tr: 'Meslekler' } },
    
    { code: 'professionpresettingscreen',       text: { en: 'Profession pre settings Screen',      tr: 'Meslek Ön Ayarları Veri' },             group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingview',         text: { en: 'Profession pre settings View',        tr: 'Meslek Ön Ayarları Görüntüleme' },      group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingadd',          text: { en: 'Profession pre settings Add',         tr: 'Meslek Ön Ayarları Oluşturma' },        group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingupdate',       text: { en: 'Profession pre settings Update',      tr: 'Meslek Ön Ayarları Güncelleme' },       group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingsavepreview',  text: { en: 'Profession pre settings Save Preview',tr: 'Meslek Ön Ayarları Taslak Kayıt Etme' },group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingapprove',      text: { en: 'Profession pre settings Approve',     tr: 'Meslek Ön Ayarları Onaylama' },         group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingcomplete',     text: { en: 'Profession pre settings Complete',    tr: 'Meslek Ön Ayarları Tamamlama' },        group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingdelete',       text: { en: 'Profession pre settings Delete',      tr: 'Meslek Ön Ayarları Silme' },            group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingmanageview',   text: { en: 'Profession pre settings Manage View', tr: 'Meslek Ön Ayarları Görünüm Ayarlama' }, group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettinggetreport',    text: { en: 'Profession pre settings Get Report',  tr: 'Meslek Ön Ayarları Rapor Alma' },       group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    { code: 'professionpresettingnotification', text: { en: 'Profession pre settings Notification',tr: 'Meslek Ön Ayarları Bildirim Alma' },    group: { en: 'Profession Pre Settings', tr: 'Meslek Ön Ayarları' } },
    
    { code: 'personelpresettingscreen',       text: { en: 'Personel pre settings Screen',      tr: 'Personel Ön Ayarları Veri' },             group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingview',         text: { en: 'Personel pre settings View',        tr: 'Personel Ön Ayarları Görüntüleme' },      group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingadd',          text: { en: 'Personel pre settings Add',         tr: 'Personel Ön Ayarları Oluşturma' },        group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingupdate',       text: { en: 'Personel pre settings Update',      tr: 'Personel Ön Ayarları Güncelleme' },       group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingsavepreview',  text: { en: 'Personel pre settings Save Preview',tr: 'Personel Ön Ayarları Taslak Kayıt Etme' },group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingapprove',      text: { en: 'Personel pre settings Approve',     tr: 'Personel Ön Ayarları Onaylama' },         group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingcomplete',     text: { en: 'Personel pre settings Complete',    tr: 'Personel Ön Ayarları Tamamlama' },        group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingdelete',       text: { en: 'Personel pre settings Delete',      tr: 'Personel Ön Ayarları Silme' },            group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingmanageview',   text: { en: 'Personel pre settings Manage View', tr: 'Personel Ön Ayarları Görünüm Ayarlama' }, group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettinggetreport',    text: { en: 'Personel pre settings Get Report',  tr: 'Personel Ön Ayarları Rapor Alma' },       group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    { code: 'personelpresettingnotification', text: { en: 'Personel pre settings Notification',tr: 'Personel Ön Ayarları Bildirim Alma' },    group: { en: 'Personel Pre Settings', tr: 'Personel Ön Ayarları' } },
    
    { code: 'personelshiftscreen',       text: { en: 'Personel shifts Screen',        tr: 'Personel Vardiyaları Veri' },               group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftview',         text: { en: 'Personel shifts View',          tr: 'Personel Vardiyaları Görüntüleme' },        group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftadd',          text: { en: 'Personel shifts Add',           tr: 'Personel Vardiyaları Oluşturma' },          group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftupdate',       text: { en: 'Personel shifts Update',        tr: 'Personel Vardiyaları Güncelleme' },         group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftsavepreview',  text: { en: 'Personel shifts Save Preview',  tr: 'Personel Vardiyaları Taslak Kayıt Etme' },  group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftapprove',      text: { en: 'Personel shifts Approve',       tr: 'Personel Vardiyaları Onaylama' },           group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftcomplete',     text: { en: 'Personel shifts Complete',      tr: 'Personel Vardiyaları Tamamlama' },          group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftfastcreate',   text: { en: 'Personel shifts Fast Create',   tr: 'Personel Vardiyaları Hızlı Oluşturma' },    group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftdelete',       text: { en: 'Personel shifts Delete',        tr: 'Personel Vardiyaları Silme' },              group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftmanageview',   text: { en: 'Personel shifts Manage View',   tr: 'Personel Vardiyaları Görünüm Ayarlama' },   group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftgetreport',    text: { en: 'Personel shifts Get Report',    tr: 'Personel Vardiyaları Rapor Alma' },         group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    { code: 'personelshiftnotification', text: { en: 'Personel shifts Notification',  tr: 'Personel Vardiyaları Bildirim Alma' },      group: { en: 'Personel Shifts', tr: 'Personel Vardiyaları' } },
    
    { code: 'stocktypescreen',       text: { en: 'Stocktypes Screen',      tr: 'Stok Türleri Veri' },             group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    { code: 'stocktypeview',         text: { en: 'Stocktypes View',        tr: 'Stok Türleri Görüntüleme' },      group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    { code: 'stocktypeadd',          text: { en: 'Stocktypes Add',         tr: 'Stok Türleri Oluşturma' },        group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    { code: 'stocktypeupdate',       text: { en: 'Stocktypes Update',      tr: 'Stok Türleri Güncelleme' },       group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    { code: 'stocktypedelete',       text: { en: 'Stocktypes Delete',      tr: 'Stok Türleri Silme' },            group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    { code: 'stocktypemanageview',   text: { en: 'Stocktypes Manage View', tr: 'Stok Türleri Görünüm Ayarlama' }, group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    { code: 'stocktypegetreport',    text: { en: 'Stocktypes Get Report',  tr: 'Stok Türleri Rapor Alma' },       group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    { code: 'stocktypenotification', text: { en: 'Stocktypes Notification',tr: 'Stok Türleri Bildirim Alma' },    group: { en: 'Stocktypes', tr: 'Stok Türleri' } },
    
    { code: 'stocktypegroupscreen',       text: { en: 'Stocktypegroups Screen',      tr: 'Stok Tür Grupları Veri' },             group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    { code: 'stocktypegroupview',         text: { en: 'Stocktypegroups View',        tr: 'Stok Tür Grupları Görüntüleme' },      group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    { code: 'stocktypegroupadd',          text: { en: 'Stocktypegroups Add',         tr: 'Stok Tür Grupları Oluşturma' },        group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    { code: 'stocktypegroupupdate',       text: { en: 'Stocktypegroups Update',      tr: 'Stok Tür Grupları Güncelleme' },       group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    { code: 'stocktypegroupdelete',       text: { en: 'Stocktypegroups Delete',      tr: 'Stok Tür Grupları Silme' },            group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    { code: 'stocktypegroupmanageview',   text: { en: 'Stocktypegroups Manage View', tr: 'Stok Tür Grupları Görünüm Ayarlama' }, group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    { code: 'stocktypegroupgetreport',    text: { en: 'Stocktypegroups Get Report',  tr: 'Stok Tür Grupları Rapor Alma' },       group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    { code: 'stocktypegroupnotification', text: { en: 'Stocktypegroups Notification',tr: 'Stok Tür Grupları Bildirim Alma' },    group: { en: 'Stocktypegroups', tr: 'Stok Tür Grupları' } },
    
    { code: 'claimpaymentparameterscreen',       text: { en: 'Claimpaymentparameters Screen',      tr: 'Hakediş Parametreleri Veri' },             group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparameterview',         text: { en: 'Claimpaymentparameters View',        tr: 'Hakediş Parametreleri Görüntüleme' },      group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparameteradd',          text: { en: 'Claimpaymentparameters Add',         tr: 'Hakediş Parametreleri Oluşturma' },        group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparameterupdate',       text: { en: 'Claimpaymentparameters Update',      tr: 'Hakediş Parametreleri Güncelleme' },       group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparametersavepreview',  text: { en: 'Claimpaymentparameters Save Preview',tr: 'Hakediş Parametreleri Taslak Kayıt Etme' },group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparameterapprove',      text: { en: 'Claimpaymentparameters Approve',     tr: 'Hakediş Parametreleri Onaylama' },         group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparameterdelete',       text: { en: 'Claimpaymentparameters Delete',      tr: 'Hakediş Parametreleri Silme' },            group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparametermanageview',   text: { en: 'Claimpaymentparameters Manage View', tr: 'Hakediş Parametreleri Görünüm Ayarlama' }, group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparametergetreport',    text: { en: 'Claimpaymentparameters Get Report',  tr: 'Hakediş Parametreleri Rapor Alma' },       group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    { code: 'claimpaymentparameternotification', text: { en: 'Claimpaymentparameters Notification',tr: 'Hakediş Parametreleri Bildirim Alma' },    group: { en: 'Claimpaymentparameters', tr: 'Hakediş Parametreleri' } },
    
    { code: 'patienteventdefinescreen',       text: { en: 'Patient Event Define Screen',      tr: 'Hasta Vaka Tanımları Veri' },             group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    { code: 'patienteventdefineview',         text: { en: 'Patient Event Define View',        tr: 'Hasta Vaka Tanımları Görüntüleme' },      group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    { code: 'patienteventdefineadd',          text: { en: 'Patient Event Define Add',         tr: 'Hasta Vaka Tanımları Oluşturma' },        group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    { code: 'patienteventdefineupdate',       text: { en: 'Patient Event Define Update',      tr: 'Hasta Vaka Tanımları Güncelleme' },       group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    { code: 'patienteventdefinedelete',       text: { en: 'Patient Event Define Delete',      tr: 'Hasta Vaka Tanımları Silme' },            group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    { code: 'patienteventdefinemanageview',   text: { en: 'Patient Event Define Manage View', tr: 'Hasta Vaka Tanımları Görünüm Ayarlama' }, group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    { code: 'patienteventdefinegetreport',    text: { en: 'Patient Event Define Get Report',  tr: 'Hasta Vaka Tanımları Rapor Alma' },       group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    { code: 'patienteventdefinenotification', text: { en: 'Patient Event Define Notification',tr: 'Hasta Vaka Tanımları Bildirim Alma' },    group: { en: 'Patienteventdefines', tr: 'Hasta Vaka Tanımları' } },
    
    { code: 'patienthealthcasedefinescreen',       text: { en: 'Patient Health Case Defines Screen',      tr: 'Hasta Sağlık Durumu Tanımı Veri' },             group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
    { code: 'patienthealthcasedefineview',         text: { en: 'Patient Health Case Defines View',        tr: 'Hasta Sağlık Durumu Tanımı Görüntüleme' },      group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
    { code: 'patienthealthcasedefineadd',          text: { en: 'Patient Health Case Defines Add',         tr: 'Hasta Sağlık Durumu Tanımı Oluşturma' },        group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
    { code: 'patienthealthcasedefineupdate',       text: { en: 'Patient Health Case Defines Update',      tr: 'Hasta Sağlık Durumu Tanımı Güncelleme' },       group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
    { code: 'patienthealthcasedefinedelete',       text: { en: 'Patient Health Case Defines Delete',      tr: 'Hasta Sağlık Durumu Tanımı Silme' },            group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
    { code: 'patienthealthcasedefinemanageview',   text: { en: 'Patient Health Case Defines Manage View', tr: 'Hasta Sağlık Durumu Tanımı Görünüm Ayarlama' }, group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
    { code: 'patienthealthcasedefinegetreport',    text: { en: 'Patient Health Case Defines Get Report',  tr: 'Hasta Sağlık Durumu Tanımı Rapor Alma' },       group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
    { code: 'patienthealthcasedefinenotification', text: { en: 'Patient Health Case Defines Notification',tr: 'Hasta Sağlık Durumu Tanımı Bildirim Alma' },    group: { en: 'Patienthealthcasedefines', tr: 'Hasta Sağlık Tanımları' } },
  
    { code: 'claimpaymentscreen',       text: { en: 'Claimpayments Screen',      tr: 'Hakedişler Veri' },             group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentview',         text: { en: 'Claimpayments View',        tr: 'Hakedişler Görüntüleme' },      group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentadd',          text: { en: 'Claimpayments Add',         tr: 'Hakedişler Oluşturma' },        group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentupdate',       text: { en: 'Claimpayments Update',      tr: 'Hakedişler Güncelleme' },       group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentapprove',      text: { en: 'Claimpayments Approve',     tr: 'Hakedişler Onaylama' },         group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentsavepreview',  text: { en: 'Claimpayments Save Preview',tr: 'Hakedişler Taslak Kayıt Etme' },group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentdelete',       text: { en: 'Claimpayments Delete',      tr: 'Hakedişler Silme' },            group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentmanageview',   text: { en: 'Claimpayments Manage View', tr: 'Hakedişler Görünüm Ayarlama' }, group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentgetreport',    text: { en: 'Claimpayments Get Report',  tr: 'Hakedişler Rapor Alma' },       group: { en: 'Claimpayments', tr: 'Hakedişler' } },
    { code: 'claimpaymentnotification', text: { en: 'Claimpayments Notification',tr: 'Hakedişler Bildirim Alma' },    group: { en: 'Claimpayments', tr: 'Hakedişler' } },
  
    { code: 'patienthealthcasescreen',       text: { en: 'Patient Health Case Screen',      tr: 'Hasta Sağlık Durumu Veri' },             group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
    { code: 'patienthealthcaseview',         text: { en: 'Patient Health Case View',        tr: 'Hasta Sağlık Durumu Görüntüleme' },      group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
    { code: 'patienthealthcaseadd',          text: { en: 'Patient Health Case Add',         tr: 'Hasta Sağlık Durumu Oluşturma' },        group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
    { code: 'patienthealthcaseupdate',       text: { en: 'Patient Health Case Update',      tr: 'Hasta Sağlık Durumu Güncelleme' },       group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
    { code: 'patienthealthcasedelete',       text: { en: 'Patient Health Case Delete',      tr: 'Hasta Sağlık Durumu Silme' },            group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
    { code: 'patienthealthcasemanageview',   text: { en: 'Patient Health Case Manage View', tr: 'Hasta Sağlık Durumu Görünüm Ayarlama' }, group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
    { code: 'patienthealthcasegetreport',    text: { en: 'Patient Health Case Get Report',  tr: 'Hasta Sağlık Durumu Rapor Alma' },       group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
    { code: 'patienthealthcasenotification', text: { en: 'Patient Health Case Notification',tr: 'Hasta Sağlık Durumu Bildirim Alma' },    group: { en: 'Patient Health Case', tr: 'Hasta Sağlık Durumları' } },
  
    { code: 'patientvisitscreen',       text: { en: 'Patient Visit Screen',      tr: 'Hasta Ziyatleri Veri' },             group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitview',         text: { en: 'Patient Visit View',        tr: 'Hasta Ziyatleri Görüntüleme' },      group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitadd',          text: { en: 'Patient Visit Add',         tr: 'Hasta Ziyatleri Oluşturma' },        group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitupdate',       text: { en: 'Patient Visit Update',      tr: 'Hasta Ziyatleri Güncelleme' },       group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitsavepreview',  text: { en: 'Patient Visit Save Preview',tr: 'Hasta Ziyatleri Taslak Kayıt Etme' },group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitapprove',      text: { en: 'Patient Visit Approve',     tr: 'Hasta Ziyatleri Onaylama' },         group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitcomplete',     text: { en: 'Patient Visit Complete',    tr: 'Hasta Ziyatleri Tamamlama' },        group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitdelete',       text: { en: 'Patient Visit Delete',      tr: 'Hasta Ziyatleri Silme' },            group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitmanageview',   text: { en: 'Patient Visit Manage View', tr: 'Hasta Ziyatleri Görünüm Ayarlama' }, group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitgetreport',    text: { en: 'Patient Visit Get Report',  tr: 'Hasta Ziyatleri Rapor Alma' },       group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
    { code: 'patientvisitnotification', text: { en: 'Patient Visit Notification',tr: 'Hasta Ziyatleri Bildirim Alma' },    group: { en: 'Patient Visits', tr: 'Hasta Ziyaretleri' } },
  
    { code: 'surveyscreen',       text: { en: 'Surveys Screen',        tr: 'Anketler Veri' },              group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveyview',         text: { en: 'Surveys View',          tr: 'Anketler Görüntüleme' },       group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveyadd',          text: { en: 'Surveys Add',           tr: 'Anketler Oluşturma' },         group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveyupdate',       text: { en: 'Surveys Update',        tr: 'Anketler Güncelleme' },        group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveysavepreview',  text: { en: 'Surveys Save Preview',  tr: 'Anketler Taslak Kayıt Etme' }, group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveyapprove',      text: { en: 'Surveys Approve',       tr: 'Anketler Onaylama' },          group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveyclear',        text: { en: 'Surveys Clear',         tr: 'Anketler Temizleme' },         group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveycomplete',     text: { en: 'Surveys Complete',      tr: 'Anketler Tamamlama' },         group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveyfill',         text: { en: 'Surveys Fill',          tr: 'Anketler Doldurma' },          group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveyremoveanswer', text: { en: 'Surveys Remove Answer', tr: 'Anketler Cevap Silme' },       group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveydelete',       text: { en: 'Surveys Delete',        tr: 'Anketler Silme' },             group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveymanageview',   text: { en: 'Surveys Manage View',   tr: 'Anketler Görünüm Ayarlama' },  group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveygetreport',    text: { en: 'Surveys Get Report',    tr: 'Anketler Rapor Alma' },        group: { en: 'Surveys', tr: 'Anketler' } },
    { code: 'surveynotification', text: { en: 'Surveys Notification',  tr: 'Anketler Bildirim Alma' },     group: { en: 'Surveys', tr: 'Anketler' } },
  
    { code: 'trainingscreen',       text: { en: 'Trainings Screen',           tr: 'Eğitimler Veri' },                  group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingview',         text: { en: 'Trainings View',             tr: 'Eğitimler Görüntüleme' },           group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingadd',          text: { en: 'Trainings Add',              tr: 'Eğitimler Oluşturma' },             group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingupdate',       text: { en: 'Trainings Update',           tr: 'Eğitimler Güncelleme' },            group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingapprove',      text: { en: 'Trainings Approve',          tr: 'Eğitimler Onaylama' },              group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingsavepreview',  text: { en: 'Trainings Save Preview',     tr: 'Eğitimler Taslak Kayıt Etme' },     group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingcompleteuser', text: { en: 'Trainings Self Complete',    tr: 'Eğitimler Bireysel Tamamlama' },    group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingcomplete',     text: { en: 'Trainings Complete',         tr: 'Eğitimler Tamamlama' },             group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingcompleteall',  text: { en: 'Trainings Complete For All', tr: 'Eğitimler Herkes İçin Tamamlama' }, group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingdelete',       text: { en: 'Trainings Delete',           tr: 'Eğitimler Silme' },                 group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingmanageview',   text: { en: 'Trainings Manage View',      tr: 'Eğitimler Görünüm Ayarlama' },      group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'traininggetreport',    text: { en: 'Trainings Get Report',       tr: 'Eğitimler Rapor Alma' },            group: { en: 'Trainings', tr: 'Eğitimler' } },
    { code: 'trainingnotification', text: { en: 'Trainings Notification',     tr: 'Eğitimler Bildirim Alma' },         group: { en: 'Trainings', tr: 'Eğitimler' } },
  
    { code: 'patienteventmovementscreen',       text: { en: 'Patient Event Movements Screen',      tr: 'Hasta Vaka Hareketleri Veri' },             group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
    { code: 'patienteventmovementview',         text: { en: 'Patient Event Movements View',        tr: 'Hasta Vaka Hareketleri Görüntüleme' },      group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
    { code: 'patienteventmovementadd',          text: { en: 'Patient Event Movements Add',         tr: 'Hasta Vaka Hareketleri Oluşturma' },        group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
    { code: 'patienteventmovementupdate',       text: { en: 'Patient Event Movements Update',      tr: 'Hasta Vaka Hareketleri Güncelleme' },       group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
    { code: 'patienteventmovementdelete',       text: { en: 'Patient Event Movements Delete',      tr: 'Hasta Vaka Hareketleri Silme' },            group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
    { code: 'patienteventmovementmanageview',   text: { en: 'Patient Event Movements Manage View', tr: 'Hasta Vaka Hareketleri Görünüm Ayarlama' }, group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
    { code: 'patienteventmovementgetreport',    text: { en: 'Patient Event Movements Get Report',  tr: 'Hasta Vaka Hareketleri Rapor Alma' },       group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
    { code: 'patienteventmovementnotification', text: { en: 'Patient Event Movements Notification',tr: 'Hasta Vaka Hareketleri Bildirim Alma' },    group: { en: 'Patient Event Movements', tr: 'Hasta Vaka Hareketleri' } },
  
    { code: 'mainteanceplanscreen',       text: { en: 'Mainteance Plans Screen',        tr: 'Periyodik Bakım Planları Veri' },               group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplanview',         text: { en: 'Mainteance Plans View',          tr: 'Periyodik Bakım Planları Görüntüleme' },        group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplanadd',          text: { en: 'Mainteance Plans Add',           tr: 'Periyodik Bakım Planları Oluşturma' },          group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplanupdate',       text: { en: 'Mainteance Plans Update',        tr: 'Periyodik Bakım Planları Güncelleme' },         group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplansavepreview',  text: { en: 'Mainteance Plans Save Preview',  tr: 'Periyodik Bakım Planları Taslak Kayıt Etme' },  group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplanapprove',      text: { en: 'Mainteance Plans Approve',       tr: 'Periyodik Bakım Planları Onaylama' },           group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplancomplete',     text: { en: 'Mainteance Plans Complete',      tr: 'Periyodik Bakım Planları Tamamlama' },          group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplandelete',       text: { en: 'Mainteance Plans Delete',        tr: 'Periyodik Bakım Planları Silme' },              group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplanmanageview',   text: { en: 'Mainteance Plans Manage View',   tr: 'Periyodik Bakım Planları Görünüm Ayarlama' },   group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplangetreport',    text: { en: 'Mainteance Plans Get Report',    tr: 'Periyodik Bakım Planları Rapor Alma' },         group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
    { code: 'mainteanceplannotification', text: { en: 'Mainteance Plans Notification',  tr: 'Periyodik Bakım Planları Bildirim Alma' },      group: { en: 'Mainteance Plans', tr: 'Periyodik Bakım Planları' } },
  
    { code: 'userincidentscreen',       text: { en: 'User Incidents Screen',        tr: 'Personel Olayları Veri' },               group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentview',         text: { en: 'User Incidents View',          tr: 'Personel Olayları Görüntüleme' },        group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentadd',          text: { en: 'User Incidents Add',           tr: 'Personel Olayları Oluşturma' },          group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentupdate',       text: { en: 'User Incidents Update',        tr: 'Personel Olayları Güncelleme' },         group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentapprove',      text: { en: 'User Incidents Approve',       tr: 'Personel Olayları Onaylama' },           group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentsavepreview',  text: { en: 'User Incidents Save Preview',  tr: 'Personel Olayları Taslak Kayıt Etme' },  group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentcomplete',     text: { en: 'User Incidents Complete',      tr: 'Personel Olayları Tamamlama' },          group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentdelete',       text: { en: 'User Incidents Delete',        tr: 'Personel Olayları Silme' },              group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentmanageview',   text: { en: 'User Incidents Manage View',   tr: 'Personel Olayları Görünüm Ayarlama' },   group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentgetreport',    text: { en: 'User Incidents Get Report',    tr: 'Personel Olayları Rapor Alma' },         group: { en: 'User Incidents', tr: 'Personel Olayları' } },
    { code: 'userincidentnotification', text: { en: 'User Incidents Notification',  tr: 'Personel Olayları Bildirim Alma' },      group: { en: 'User Incidents', tr: 'Personel Olayları' } },
  
    { code: 'patientactivityscreen',       text: { en: 'Patient Activity Screen',       tr: 'Hasta Aktivete Veri' },              group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivityview',         text: { en: 'Patient Activity View',         tr: 'Hasta Aktivete Görüntüleme' },       group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivityadd',          text: { en: 'Patient Activity Add',          tr: 'Hasta Aktivete Oluşturma' },         group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivityupdate',       text: { en: 'Patient Activity Update',       tr: 'Hasta Aktivete Güncelleme' },        group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivitysavepreview',  text: { en: 'Patient Activity Save Preview', tr: 'Hasta Aktivete Taslak Kayıt Etme' }, group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivityapprove',      text: { en: 'Patient Activity Approve',      tr: 'Hasta Aktivete Onaylama' },          group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivitycomplete',     text: { en: 'Patient Activity Complete',     tr: 'Hasta Aktivete Tamamlama' },         group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivitydelete',       text: { en: 'Patient Activity Delete',       tr: 'Hasta Aktivete Silme' },             group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivitymanageview',   text: { en: 'Patient Activity Manage View',  tr: 'Hasta Aktivete Görünüm Ayarlama' },  group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivitygetreport',    text: { en: 'Patient Activity Get Report',   tr: 'Hasta Aktivete Rapor Alma' },        group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
    { code: 'patientactivitynotification', text: { en: 'Patient Activity Notification', tr: 'Hasta Aktivete Bildirim Alma' },     group: { en: 'Patient Activities', tr: 'Hasta Aktiviteleri' } },
  
    { code: 'patientroutinescreen',       text: { en: 'Patient Routine Screen',       tr: 'Hasta Rutinleri Veri' },              group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
    { code: 'patientroutineview',         text: { en: 'Patient Routine View',         tr: 'Hasta Rutinleri Görüntüleme' },       group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
    { code: 'patientroutineadd',          text: { en: 'Patient Routine Add',          tr: 'Hasta Rutinleri Oluşturma' },         group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
    { code: 'patientroutineupdate',       text: { en: 'Patient Routine Update',       tr: 'Hasta Rutinleri Güncelleme' },        group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
    { code: 'patientroutinedelete',       text: { en: 'Patient Routine Delete',       tr: 'Hasta Rutinleri Silme' },             group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
    { code: 'patientroutinemanageview',   text: { en: 'Patient Routine Manage View',  tr: 'Hasta Rutinleri Görünüm Ayarlama' },  group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
    { code: 'patientroutinegetreport',    text: { en: 'Patient Routine Get Report',   tr: 'Hasta Rutinleri Rapor Alma' },        group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
    { code: 'patientroutinenotification', text: { en: 'Patient Routine Notification', tr: 'Hasta Rutinleri Bildirim Alma' },     group: { en: 'Patient Routines', tr: 'Hasta Rutinleri' } },
  
    ]
    
    module.exports = Priveleges