export const STORAGE_KEY_ACCESSTOKEN = 'APP_STORAGE_KEY_1'

export const STORAGE_KEY_REFRESHTOKEN = 'APP_STORAGE_KEY_2'

export const STORAGE_KEY_LANGUAGE = 'APP_STORAGE_KEY_3'

export const STORAGE_KEY_EXPIRETIME = 'APP_STORAGE_KEY_4'

export const STORAGE_KEY_SHOWEDVERSION = 'APP_STORAGE_KEY_5'

export const API_FETCH_ERROR = "FETCH_ERROR"

export const API_UNAUTHORIZE_ERROR = 401

export const MEDIA_BREAKDOWN_POINT_MOBILE_LARGE = 425

export const MEDIA_BREAKDOWN_POINT = 768

export const GENDER_OPTION_MEN = "0"

export const GENDER_OPTION_WOMEN = "1"

export const ANNUAL_TYPE_WORKING = 0

export const ANNUAL_TYPE_FREE = 1

export const USERNAME_REGEX = /^[a-z][a-z0-9]{2,24}$/

export const PASSWORD_REGEX = /^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&.])[A-Za-z\d@$!%*?&.]{8,}$/

export const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;

export const PAYMENTTYPE_TYPE_INVOICE = 0

export const PAYMENTTYPE_TYPE_INSTALLMENT = 1

export const PAYMENTTYPE_TYPE_CREDITCARD = 2

export const PAYMENTTYPE_TYPE_BANKTRANSFER = 3

export const PAYMENTTYPE_TYPE_CASH = 4

export const STOCK_SOURCETYPE_USER = 0

export const STOCK_SOURCETYPE_PURCHASEORDER = 1

export const STOCK_SOURCETYPE_VISIT = 2

export const VISIT_STATU_PLANNED = 0

export const VISIT_STATU_WORKING = 1

export const VISIT_STATU_COMPLETED = 2

export const VISIT_STATU_ON_APPROVE = 3

export const VISIT_STATU_CLOSED = 4

export const VISIT_PAYMENT_STATUS_NON = 0

export const VISIT_PAYMENT_STATUS_SEMI = 1

export const VISIT_PAYMENT_STATUS_FULL = 2

export const PAYMENT_TRANSACTION_TYPE_PREPAYMENT = 0

export const PAYMENT_TRANSACTION_TYPE_FULLPAYMENT = 1

export const PAYMENT_TRANSACTION_TYPE_TRANSACTION = 2

export const PAYMENT_TRANSACTION_TYPE_CLOSE_TRANSACTION = 3

export const VISIT_TYPE_SALEVISIT = 0

export const VISIT_TYPE_FREEVISIT = 1

export const PAYMENT_TRANSACTION_TYPE_INCOME = 1

export const PAYMENT_TRANSACTION_TYPE_PASSIVE = 0

export const PAYMENT_TRANSACTION_TYPE_OUTCOME = -1

export const FLOW_TYPE_VISIT = 0

export const FLOW_TYPE_MANUEL = 1